### ISSUE TITLE
Simple Pebs giving kernel paging error

### ISSUE THREAD

**Issue by richa-saraf** [andikleen/pmu-tools#104]
uname -r: 
4.13.0-32-generic

simple-pebs giving conflict issues due to changes in intel_ds.h file. 
After resolving those issues, the driver is giving the following error(No other changes done):
 
simple_pebs: Initialized
kernel: [11442.158413] BUG: unable to handle kernel paging request at ffff9d6c14e52038
kernel: [11442.158461] IP: 0x55925f7d11ac
kernel: [11442.158478] PGD 21632a067
kernel: [11442.158479] P4D 21632a067
kernel: [11442.158492] PUD 3fa0b6063
kernel: [11442.158502] PMD 3d4f24063
kernel: [11442.158512] PTE 80000003d4e52063
kernel: [11442.158522]
kernel: [    0.000000] random: get_random_bytes called from start_kernel+0x42/0x504 with crng_init=0

**Comment by andikleen** [comment]
Likely was due to page table separation, which has been fixed some time ago.
