### ISSUE TITLE
Event_download.py Failure, File Not Found

### ISSUE THREAD

**Issue by AlanCarey** [andikleen/pmu-tools#112]
During the download of Intel core json files I get this error related to a file not fond. 

![image](https://user-images.githubusercontent.com/9608764/38501077-0a2e5188-3c04-11e8-9761-18ff81fa5de5.png)

I found that the error is related to the mapfile.csv being parse by event_download.py and the json file it tires to download.

So the file it tries to download is this: https://download.01.org/perfmon/SNB/sandybridge_core_v16.json
But first the script parses this file for the respective json to download: https://download.01.org/perfmon/mapfile.csv

So:

In mapfile: SNB/sandybridge_core_V16.json
Actual file: SNB/sandybridge_core_v16.json

The difference being the upper/lower 'v' that causes the problem.

Possible fix would be to talk with whoever runs the site related to mapfile.csv and ensure the information is mapped correctly.

Another fix would be to make sure the file exists first and if not change the case of the 'v' & download again.

**Comment by andikleen** [comment]
On Mon, Apr 09, 2018 at 01:57:24PM +0000, AlanCarey wrote:
> During the download of Intel core json files I get this error related to a file
> not fond.
> 
> image
> 
> I found that the error is related to the mapfile.csv being parse by
> event_download.py and the json file it tires to download.
> 
> So the file it tries to download is this: https://download.01.org/perfmon/SNB/
> sandybridge_core_v16.json
> But first the script parses this file for the respective json to download:
> https://download.01.org/perfmon/mapfile.csv
> 
> So:
> 
> In mapfile: SNB/sandybridge_core_V16.json
> Actual file: SNB/sandybridge_core_v16.json
> 
> The difference being the upper/lower 'v' that causes the problem.
> 
> Possible fix would be to talk with whoever runs the site related to mapfile.csv
> and ensure the information is mapped correctly.
> 
> Another fix would be to make sure the file exists first and if not change the
> case of the 'v' & download again.

Thanks for the report. Should be fixed now.
