### ISSUE TITLE
perf report support for HITM events

### ISSUE THREAD

**Issue by takhandipu** [andikleen/pmu-tools#114]
I can use `ocperf.py stat` to count HITM events however, `ocperf.py` record cannot record such events. For example, When I run the command,
`ocperf.py stat -e mem_load_uops_l3_hit_retired.xsnp_hitm ./tensor_parallel`
I get following output,
```
perf stat -e cpu/event=0xd2,umask=0x4,name=mem_load_uops_l3_hit_retired_xsnp_hitm/ ./tensor_parallel

 Performance counter stats for './tensor_parallel':

            78,858      mem_load_uops_l3_hit_retired_xsnp_hitm                                   

       0.584347709 seconds time elapsed

```
However, if I run the command,
`ocperf.py record -e mem_load_uops_l3_hit_retired.xsnp_hitm ./tensor_parallel`
output
```
perf record -e cpu/event=0xd2,umask=0x4,name=mem_load_uops_l3_hit_retired_xsnp_hitm,period=20011/ ./tensor_parallel
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.023 MB perf.data ]
```
and then,
`ocperf.py report`
my output is empty:
```
┌─Error:───────────────────────────┐
│The perf.data file has no samples!│
│                                  │
│                                  │
│Press any key...                  │
└──────────────────────────────────┘
```
Does perf report support these hitm events? If yes, what am I doing wrong? If not, how can it be implemented?

**Comment by andikleen** [comment]
On Fri, Apr 20, 2018 at 02:18:40PM -0700, Tanvir Ahmed Khan wrote:
> I can use ocperf.py stat to count HITM events however, ocperf.py record cannot
> record such events. For example, When I run the command,
> ocperf.py stat -e mem_load_uops_l3_hit_retired.xsnp_hitm ./tensor_parallel
> I get following output,
> 
> perf stat -e cpu/event=0xd2,umask=0x4,name=mem_load_uops_l3_hit_retired_xsnp_hitm/ ./tensor_parallel
> 
>  Performance counter stats for './tensor_parallel':
> 
>             78,858      mem_load_uops_l3_hit_retired_xsnp_hitm
> 
>        0.584347709 seconds time elapsed
> 
> 
> However, if I run the command,
> ocperf.py record -e mem_load_uops_l3_hit_retired.xsnp_hitm ./tensor_parallel
> output
> 
> [ perf record: Woken up 1 times to write data ]
> [ perf record: Captured and wrote 0.023 MB perf.data ]
> 
> and then,
> ocperf.py report
> my output is empty:
> 
> ┌─Error:───────────────────────────┐
> │The perf.data file has no samples!│
> │                                  │
> │                                  │
> │Press any key...                  │
> └──────────────────────────────────┘
> 
> Does perf report support these hitm events? If yes, what am I doing wrong? If
> not, how can it be implemented?

Probably you just didn't have enough events to sample. The default period is 20k+, so at 78k
that would be only a few samples and perhaps some gost lost.

You can edit the resulting line to have a lower period, or better run your workload for longer.

ocperf should probably have better ways to override the period.

**Comment by takhandipu** [comment]
I have been able to get the report by changing the period reducing from 20011 to 1001 and running my program for a larger dataset. Thank you for the help.
