### ISSUE TITLE
KNL Silvermont - TAM With Level 1 to 4

### ISSUE THREAD

**Issue by ChetanArvindPatil** [andikleen/pmu-tools#115]
Hi Andi,

I have KNL Silvermont and trying to get TAM done on it. The [KNL ratios](https://github.com/andikleen/pmu-tools/blob/master/knl_ratios.py) are derived from [Silvermont source](https://github.com/andikleen/pmu-tools/blob/master/slm_ratios.py) here.

But this contains only Level 1 and then frontend's Level 2 to 4. Shouldn't the TAM include all the levels from Level 1 to 4 for each of frond end, bad speculation, backend bound and retiring?

Thanks.

**Comment by andikleen** [comment]
We only a single level on Atom and Knights currently, sorry.

**Comment by PatilChetan** [comment]
Hi Andi,

On Intel Forum, a document was [shared on TAM on KNL](https://software.intel.com/en-us/forums/software-tuning-performance-optimization-platform-monitoring/topic/777241#comment-1921611).

If you plan to integrate level 2 and 3, will the counters in above linked sheet be valid? I can do this on my own using perf as long as the counters are correct for level 2 and 3. I am not sure why there isn't a level 4 for KNL.

Thanks.

**Comment by andikleen** [comment]
Interesting. I wasn't aware of the KNL spreadsheet.

I don't know how well it works. You have to try it. I guess should be added to toplev.
