### ISSUE TITLE
error: redefinition of ‘struct debug_store’

### ISSUE THREAD

**Issue by sanjeevk001** [andikleen/pmu-tools#116]
I am getting error while installing "simple-pebs", on ubuntu (4.13.0-39-generic). Appreciate any help.
========================================
/home/pmu-tools-master/simple-pebs/simple-pebs.c:325:8: error: redefinition of ‘struct debug_store’
 struct debug_store { 
        ^
In file included from ./arch/x86/include/asm/cpu_entry_area.h:8:0,
                 from ./arch/x86/include/asm/desc.h:9,
                 from /home/pmu-tools-master/simple-pebs/simple-pebs.c:54:
./arch/x86/include/asm/intel_ds.h:17:8: note: originally defined here
 struct debug_store {
        ^
In file included from ./include/asm-generic/percpu.h:6:0,
                 from ./arch/x86/include/asm/percpu.h:542,
                 from ./arch/x86/include/asm/preempt.h:5,
                 from ./include/linux/preempt.h:80,
                 from ./include/linux/spinlock.h:50,
                 from ./include/linux/seqlock.h:35,
                 from ./include/linux/time.h:5,
                 from ./include/linux/stat.h:18,
                 from ./include/linux/module.h:10,
                 from /home/pmu-tools-master/simple-pebs/simple-pebs.c:38:

**Comment by andikleen** [comment]
Should be fixed
