### ISSUE TITLE
What's the difference between the event of "QPI_LL.QPI_LINK_BW" and "QPI_LL.QPI_DATA_BW"

### ISSUE THREAD

**Issue by GH15zzh** [andikleen/pmu-tools#120]
Hi, 
I want to run ./ucevent.py to measure the QPI bandwidth. But I find this two event: QPI_LL.QPI_LINK_BW and QPI_LL.QPI_DATA_BW. What's the difference between them? And which value represents the QPI bandwidth？

**Comment by cmchou** [comment]
Basically not only data but also snoop traffic is transferred through QPI. I believe QPI_LL.QPI_LINK_BW and QPI_LL.QPI_DATA_BW includes the snoop traffic as well.

**Comment by GH15zzh** [comment]
When I measure the bandwidth on socket 1, "./ucevent.py --scale MB --socket 1 QPI_LL.QPI_DATA_BW QPI_LL.QPI_LINK_BW"

Here is output. It seems that the value of the two is still a little different.  So should I use the value of "QPI_LL0.QPI_DATA_BW + QPI_LL1.QPI_DATA_BW" to stand for QPI bandwidth?
`QPI_LL0.QPI_DATA_BW
|        QPI_LL1.QPI_DATA_BW
|        |        QPI_LL0.QPI_LINK_BW
|        |        |        QPI_LL1.QPI_LINK_BW
1,132.48 1,145.26 1,526.70 1,545.28 
1,133.40 1,158.72 1,549.30 1,585.80 
1,093.10 1,113.88 1,498.48 1,528.62 
596.83   585.76   821.23   805.30   
1,035.93 1,050.61 1,410.98 1,432.26 
1,247.54 1,270.82 1,695.92 1,729.53 
1,144.99 1,161.40 1,578.29 1,601.88 
487.09   494.19   676.37   686.59   
1,012.88 1,022.61 1,354.00 1,368.13 
991.60   1,013.47 1,359.13 1,390.69 
1,119.52 1,136.72 1,516.02 1,540.83 
903.34   918.89   1,229.58 1,252.29 
463.45   465.17   622.19   625.16   
1,086.15 1,098.41 1,506.50 1,524.39 
1,015.79 1,036.59 1,415.40 1,445.59 
980.17   998.36   1,369.42 1,395.80 
1,267.31 1,255.11 1,740.05 1,723.18 
1,033.68 1,056.73 1,414.41 1,447.65 
978.04   996.74   1,332.49 1,359.55 
1,125.47 1,147.72 1,542.18 1,574.45 
756.11   767.47   1,035.03 1,050.83 
1,045.97 1,049.51 1,438.23 1,443.98 
1,362.03 1,375.50 1,837.43 1,856.90 
1,152.85 1,174.15 1,561.64 1,592.62 
`
