### ISSUE TITLE
Couldn't get the retiring statistics from toplev.py

### ISSUE THREAD

**Issue by Jeongseob** [andikleen/pmu-tools#125]
Hi,

I've started to profile benchmarks with the `toplev.py` and faced with the issue which just shows the two components, `Frontend_Bound` and `Backend_Bound,` without `Retiring` and `Bad_Speculation` components. 

```
# ./toplev.py --core S0-C0 --no-desc -l1 taskset -c 0 runcpu --config=jeongseob-gcc-linux-x86.cfg --action=run 600
Will measure complete system.
Using level 1.
# 3.4-full on Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
perf stat -x\; -e '{cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0xe,umask=0x1/,cpu/event=0x9c,umask=0x1/,cpu/event=0xd,umask=0x3,any=1,cmask=1/,cpu/event=0xc2,umask=0x2/}' -C 0,24 -A -a taskset -c 0 runcpu --config=jeongseob-gcc-linux-x86.cfg --action=run 600
SPEC CPU(r) 2017 Benchmark Suites
Copyright 1995-2017 Standard Performance Evaluation Corporation (SPEC)

(omitted)

runcpu finished at 2018-07-09 16:05:20; 519 total seconds elapsed
S0-C0    FE             Frontend_Bound:         23.77 % Slots [100.00%] <==
S0-C0    BE             Backend_Bound:          11.11 % Slots [100.00%]
```

Sometimes, it shows only the `Backend_Bound` like below. Note that this is another benchmark which you can find out in the `workloads` directory.
```
# ./toplev.py --core S0-C0 --no-desc -l1 taskset -c 0 workloads/CALC10s
Will measure complete system.
Using level 1.
# 3.4-full on Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
perf stat -x\; -e '{cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0xe,umask=0x1/,cpu/event=0x9c,umask=0x1/,cpu/event=0xd,umask=0x3,any=1,cmask=1/,cpu/event=0xc2,umask=0x2/}' -C 0,24 -A -a taskset -c 0 workloads/CALC10s
S0-C0    BE             Backend_Bound:          37.84 % Slots [100.00%] <==
```

I tested the toplev without any options like `./toplev ls`, but it also didn't show the `retiring` component.

For this testing, I've been using kernel 4.9.78 and the processor used is Xeon E5-2650 v4 (Broadwell). FYI, SMT is enabled.

Thanks,
Jeongseob

**Comment by andikleen** [comment]
pmu-tools by default only displays a metric if it crosses a threshold.
So that just means the other metrics were below the threshold

**Comment by Jeongseob** [comment]
@andikleen, Okay, but the benchmark (SPECCPU) I tested is known to be cpu intensive so that I think it should show the `retiring` component. (FYI, it rans about 8 min.)  According to the slide from Ahmad Yasin, it showed the component. I am wondering you have any guess that it couldn't cross the threshold?

**Comment by andikleen** [comment]
Don't know why. I guess it depends on the sub test.

You can use -v to show values below the threshold. However the sub nodes may not be useful in this case.
