### ISSUE TITLE
not counted issue on Intel(R) Xeon(R) CPU E5620  @ 2.40GHz

### ISSUE THREAD

**Issue by zhuguoliang** [andikleen/pmu-tools#13]
Hi community!

I am using perf as :sudo perf stat -e r00c0,r01c0,r01c0:p,r01c0:pp sleep 1

but the result is 

 Performance counter stats for 'sleep 1':

           464,229 r00c0                                                       
           464,229 r01c0                                                       
     <not counted> r01c0:p                 
     <not counted> r01c0:pp                

       1.001639901 seconds time elapsed

Whys is PEBS not counted here?

Sorry to ask my question here...

Please help me on this.

**Comment by andikleen** [comment]
Question has nothing to do with pmu-tools.

**Comment by zhuguoliang** [comment]
But would you give me some advice on this?

**Comment by andikleen** [comment]
1c0 is INST_RETIRED.PREC_DIST which can only run on one counter, so it does not get scheduled This is a special case, most PEBS events don't have this limitations. However in general counting PEBS doesn't make much sense, enabling PEBS is only useful for sampling (Precise Event Based Sampling)
