### ISSUE TITLE
Puzzling  about  ICache_Misses

### ISSUE THREAD

**Issue by SimonDyl** [andikleen/pmu-tools#14]
1.why  the metric "ICache_Misses" don't be include in  jkt_server_ratios.py ?
2.what is your thinking about that "ICache Misses" formula difference with vtune?
    vtune, "ICache Misses" formula is  event("ICACHE.MISSES") / query("InstructionsRetired") 
    pmu-tools, EV("ICACHE.IFETCH_STALL", 3) / CLKS(EV, 3) - ITLB_Miss_Cycles(EV, 3) / CLKS(EV, 3 )

Thank you!

**Comment by andikleen** [comment]
The Sandy Bridge core doesn't have all events needed for full TopDown, so some nodes are missing.

The vtune formula is not a stall cycles metric, it just counts the number of misses.
