### ISSUE TITLE
Inconsistent definition of `walk_perf_events`

### ISSUE THREAD

**Issue by travisdowns** [andikleen/pmu-tools#142]
In the header `jevents.h` `walk_perf_events` is declared as:

    int walk_perf_events(int (*func)(void *data, char *name, char *event, char *desc),                  void *data)

while in the implementation `resolve.c` it is defined as:

    int walk_perf_events(int (*func)(void *data, char *name, char *event, char *desc, char *pmu), void *data)

Note the extra `pmu` parameter in the callback. In principle this is undefined behavior (I'm guessing), but in practice it probably works fine but just doens't let the caller access the `pmu` argument.

The simplest fix is to add `pmu` to the declaration, but this will break some existing users depending on how strict their compilers are (most C++ compilers and gcc will reject this AFAIK, at default settings). If that's not a concern, I can submit a pull request for that.

Another option to add a `walk_perf_events2` or whatever which exposes the `pmu` parameter.

A final option is just to stop passing the pmu to the callback at all (I guess it is already there as part of the event string).

Whatever you'd like I can implement.

**Comment by andikleen** [comment]
Thanks. Should just remove the argument for now. Should also include the header file in the right file to catch it.

Longer term we need a generic extensible way to access all the fields in the JSON. The Linux perf version of this code kept growing more and more arguments to this call back to parse more fields, but that's really ugly.

**Comment by travisdowns** [comment]
@andikleen - sure, I'll submit a pull request to that effect and include the header (good catch: that's why the compiler didn't complain I guess).

You pass a single structure I guess instead of a list of args to the callback, then you'd be able to add fields in a backwards compatible way.
