### ISSUE TITLE
Multiple read_events calls (including implicit ones) produce duplicate events

### ISSUE THREAD

**Issue by travisdowns** [andikleen/pmu-tools#146]
I noticed I was getting duplicate events when calling `walk_events` in uarch-bench, and one of the cases was that I was calling `read_events(NULL)` twice. However, even when I ensured I was only calling `read_events` once, I still had 2 copies of each event. 

This ended up being because I was calling `resolve_event` somewhere else in the code, before calling `read_events`.

Here's the code for `read_events`:

```
int read_events(char *fn)
{
	if (!eventlist_init)
		free_events();
	eventlist_init = true;
	/* ??? free on error */
	return json_events(fn, collect_events, NULL);
}
```

The upshot is that every time you call `read_events`, you call `json_events` and internally add to a growing set of events. Code like `resolve_event` does a check: `if (!eventlist_init) read_events(NULL)`, but client code like mine can't do this check, so then the result depends on the order: if you make your `read_events` call first you get only one copy of the events, but if the library call comes first you get two copies.

What I don't understand is the first part:

```
	if (!eventlist_init)
		free_events();
```

I think this code will never have any effect: if the event list is not initialized, there are no events to free. Perhaps the meaning here was the opposite:

```
	if (eventlist_init)
		free_events();
```

This now has some effect: it means that each `read_events` call replaces the prior events. This avoids duplicates, and is still efficient since internal usages only call this after checking `if (!eventlist_init)`.

I will submit a pull request to this effect, but other behaviors are possible: it isn't clear to me exactly how the global cache should be managed. Perhaps the cleanest approach is to expose eventlist structure in the API that you can pass into the various methods, with `NULL` indicating that the default cache is to be used, and then change `read_events` so the user-facing functions never mess with the global cache. I dunno.

**Comment by andikleen** [comment]
Your solution seems reasonable. I don't quite remember what I intended ) I pulled.

**Comment by travisdowns** [comment]
It should be noted that if people are calling `read_events` multiple times with different `.json` files to build up a cache this will no longer work.
