### ISSUE TITLE
jevents: offcore_response events aren't resolved properly by resolve_event

### ISSUE THREAD

**Issue by travisdowns** [andikleen/pmu-tools#148]
If you pass `offcore_response.demand_code_rd.any_response` into `resolve_event` on a system with the , it correctly finds the event in the `eventlist`, which has an event string (`e->event`) like:

`umask=0x01,period=100003,event=0xb7,offcore_rsp=0x0000010001`

This gets passed into `jevent_name_to_attr` to fill in the `perf_event_attr` object, but this method doesn't understand x86-specific named things like `offcore_rsp`: it parses only `config`, `config1`, `config2` and a few special attrs like `period` and `freq`.

So the `offcore_rsp` gets dropped and the event doesn't work. Instead it should get mapped to `config1`.

This bug is reported in terms of `offcore_response`, but it presumably applies to any event that has an extra MSR/config1 value such as the `frontend=` or `ldlat=` events.

**Comment by andikleen** [comment]
parse_terms() should understand it, it tries to look up the attribute in /sys/devices/cpu/format/
and parses it. Must be some bug in that code if it doesn't work. Should be easy to see when stepping through in gdb what goes wrong?

**Comment by travisdowns** [comment]
@andikleen - see my comment on the PR I just submitted, but the issue was in the definition of the `BITS` macro: it doesn't work for fields like `config1:0-63` because `BITS(64)` doesn't work. In fact, I don't think it worked for `BITS(x)` where `x > 31` since there was a `1U` rather than `1UL` but anyways I fixed that too.

**Comment by andikleen** [comment]
Ah that makes sense. Stupid me. I think I already pulled that one earlier

**Comment by andikleen** [comment]
Technically it needs to be 1ULL for 32bit builds, but can fix that later.

**Comment by travisdowns** [comment]
@andikleen  - yes you pulled it in the first PR but that was unintentional on my part as I meant to submit separate PRs for all of this but Github doens't work like I thought I did.

OK, I had `1ULL` originally but then I checked `bitops.h` in the kernel source and changed it since I only saw a `1UL` in there (for `BIT_MASK` for example), but yeah I guess I was checking the 64-bit source.
