### ISSUE TITLE
perf parser errors

### ISSUE THREAD

**Issue by senior7515** [andikleen/pmu-tools#158]
Given:

```
ocperf.py stat --metrics Load_Miss_Real_Latency,TLB,IPC,DSB,Frontend -d -d -d -p 1345
```

I get an error like: 

```
event syntax error: '..ss.pending,mem_load_retired.l1_miss_ps,mem_load_retired.fb_hit_ps}:W,{itlb_misses.walk_pending,dtlb_load_misses.walk_pending,dtlb_store_misses.walk_pending..'
                                  \___ parser error
```

I am looking for a workflow type of suggestion/workaround.

How does one usually work around these 

Running:
* `perf version 4.18.13`
* fedora, kernel 4.18 ` 4.18.14-200.fc28.x86_64 `

**Comment by andikleen** [comment]
--metrics is implemented in perf, not  ocperf, so it's really a perf problem.

If you remove Load_Miss_Real_Latency it should work

You can see which events it uses internally with -vv

It's a problem in the event file, if you remove the _ps suffixes in tools/perf/pmu-events/arch/x86/skylake/skl-metrics.json   (and same for skylakex/skx-metrics.jso)
and rebuild it should work

**Comment by senior7515** [comment]
got it. 

The thing is i got these groups via the `ocperf.py list` - how to list the events that this machine actually supports tho?

**Comment by andikleen** [comment]
Fixed in upstream Linux, will be in the next release
