### ISSUE TITLE
Improper handling of non-consecutive imc uncore pmu dev names

### ISSUE THREAD

**Issue by tootoonchian** [andikleen/pmu-tools#16]
On my machine (running Linux 3.19) imc uncore pmu dev names are not consecutive: i.e., instead of /sys/devices/uncore_imc_{0..3} I have /sys/devices/uncore_imc_{0,1,4,5}. But expand_events (among possibly other places in the code) assume there is no gap in naming, so I end up only two values instead of four.

As a quick/dirty workaround I modified ucexpr.py>expand_events to:

    for n in range(10):
        if ucevent.box_exists(...):
            l.append(...)

**Comment by andikleen** [comment]
Should be fixed now. Please test.

**Comment by tootoonchian** [comment]
It is fixed. Thanks.
