### ISSUE TITLE
In the SMT mode, the Pipeline_Width in the Frontend_Latency formula should be 2?

### ISSUE THREAD

**Issue by WrightChen** [andikleen/pmu-tools#171]
When I study the TMAM, I found Frontend_Latency formula:
`self.val = Pipeline_Width * EV("IDQ_UOPS_NOT_DELIVERED.CYCLES_0_UOPS_DELIV.CORE", 2) / SLOTS(self, EV, 2)
`
When in the SMT mode, the SLOTS = EV("CPU_CLK_UNHALTED.THREAD_ANY", level) / 2. So the frontend_latency.val = IDQ_UOPS_NOT_DELIVERED.CYCLES_0_UOPS_DELIV.CORE / (CPU_CLK_UNHALTED.THREAD_ANY/2). I think it should be "IDQ_UOPS_NOT_DELIVERED.CYCLES_0_UOPS_DELIV.CORE / CPU_CLK_UNHALTED.THREAD_ANY".

I don't know if the pipeline bandwidth in the Intel CPU is statically partitioned. If it's statically partitioned, the Pipeline_Width should be 2 when in the SMT mode.

Could you please give me some hints? Thank you:)

**Comment by andikleen** [comment]
It's not statically partitioned
