### ISSUE TITLE
rdpmc_read readings are not comparable when counter is scheduled vs non-scheduled

### ISSUE THREAD

**Issue by travisdowns** [andikleen/pmu-tools#173]
I have been getting bogus readings with `rdpmc_read` if the PMU is "oversubscribed" (i.e., more counters programmed than hardware counters, or at least more than the scheduler can figure how to schedule).

The invalid readings occur when one of the start/stop readings occur when the counter is scheduled, and one when it is not.

Here's an example:

```
read counter cpu_clk_unhalted.thread_p       val=0x080000373f8ca offset=0x07fffffffffff res=0x100000373f8c9 index=0x0000040000002


read counter cpu_clk_unhalted.thread_p       val=0x0000000000000 offset=0x0000003aa7e4f res=0x0000003aa7e4f index=0x0000000000000
```

The shown values are the local variables from `rdpmc_read`, with `res` being the returned result `return val + offset` or `return offset` depending on whether the `rdpmc` occurs.

First reading is start reading, with index=`0x40000002` meaning the counter is currently running and `rdpmc` can be used, and the entire value comes from `rdpmc` with `offset` being 2^47-1 (highest positive 47 bit value). I'm not sure why it's like this: I guess when the perf subsystem schedules a counter, it doesn't populate the `offset` field with the accumulated value but just restores the saved value directly into the hardware counter.

In any case, the result is `0x100000373f8c9` - note that bit 48 is set.

In the second reading, the counter has been descheduled so the payload value is in `offset` and `val` is zero (we don't even do the `rdpmc`). The result is `0x0000003aa7e4`. Bit 48 is not set. So the delta of the two values is bogus.

If we mask the result to `ctx->pmc_width`, we get the right value. Is that the right change? It isn't 100% clear to me why the `offset` is set to `0x7fffffffffff` when the counter isn't scheduled.

**Comment by travisdowns** [comment]
@andikleen - any comment? For now I'm masking the counter to `ctx->pmc_width` locally which is working seeking your insight here.

**Comment by andikleen** [comment]
I think masking is the correct fix. I added 48bit masking to the jevents code.
Correct would probably to read the CPUID enumeration for it, but for now just hardcoding 48bit should be sufficient.
