### ISSUE TITLE
toplev doesn't support "CPU model 85"

### ISSUE THREAD

**Issue by NanXiao** [andikleen/pmu-tools#177]
Hi Andi,

Greeting from me!

I use `VoidLinux` in `VirtualBox` and want to play with `toplev`:

```
# toplev.py sleep 3
Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
Downloading https://download.01.org/perfmon/SKX/skylakex_core_v1.12.json to GenuineIntel-6-55-4-core.json
Downloading https://download.01.org/perfmon/SKX/skylakex_matrix_v1.12.json to GenuineIntel-6-55-4-offcore.json
Downloading https://download.01.org/perfmon/SKX/skylakex_uncore_v1.12.json to GenuineIntel-6-55-4-uncore.json
Downloading https://download.01.org/perfmon/readme.txt to readme.txt
Unsupported CPU model 85
```

My `CPU` model is like this:  
```
# lscpu
......
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8170 CPU @ 2.10GHz
......
```

From the [code](https://github.com/andikleen/pmu-tools/blob/master/toplev.py#L44), I think `toplev` should support "`model 85`". Could you help to check it? Thanks very much!

Best Regards
Nan Xiao
```

**Comment by andikleen** [comment]
Are you running the latest version?

There was a change how the mapfile describes the skylakex model numbers,
but I thought I had fixed it.

**Comment by NanXiao** [comment]
@andikleen Yes, I use the newest version, thanks!

**Comment by NanXiao** [comment]
@andikleen After debugging, I find the root cause is following [code](https://github.com/andikleen/pmu-tools/blob/0de372d3e6c115b2897664cccfb11af2cd8b11a2/tl_cpu.py#L143):  

`if ok >= 7:`

For my case, `ok` is `6`. The following is '/proc/cpuinfo' file:  

```
# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Platinum 8170 CPU @ 2.10GHz
stepping        : 4
cpu MHz         : 2095.006
cache size      : 36608 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips        : 4190.01
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:


```

Could you help to check it? Thanks!

Best Regards
Nan Xiao

**Comment by andikleen** [comment]
Thanks for the test case. I committed some improvements to the parser. Please see if it works now.

**Comment by NanXiao** [comment]
@andikleen The issue is fixed, thanks!

**Comment by niemasd** [comment]
I'm getting the same error message with the following ``/proc/cpuinfo//:

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) CPU @ 2.00GHz
stepping        : 3
microcode       : 0x1
cpu MHz         : 2000.160
cache size      : 39424 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 4000.32
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

Any help would be greatly appreciated!

**Comment by andikleen** [comment]
On Thu, May 07, 2020 at 04:55:58PM -0700, Niema Moshiri wrote:
> I'm getting the same error message with the following ``/proc/cpuinfo//:
> 
> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 85
> model name      : Intel(R) Xeon(R) CPU @ 2.00GHz
> stepping        : 3

That's another preproduction CPU, right?

You can use --force-cpu skx or apply the patch in the issue. The
standard toplev doesn't support preproduction steppings.

**Comment by niemasd** [comment]
> That's another preproduction CPU, right?

Not too sure; this is a Google Cloud Platform VM. Sorry for my inexperience :-) I'm collaborating with some hardware people, and they asked me for some profiling info about my runs

> You can use --force-cpu skx

I tried that, and now I get the following error:

```
Cannot open /root/.cache/pmu-events/GenuineIntel-6-55-uncore.json
Cannot open /root/.cache/pmu-events/GenuineIntel-6-55-uncore.json
event syntax error: '..ref-cycles,cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0x9c,umask=0x1/,cpu/event=0xc2,umask=0x2/,cpu/event=0xd,umask=0x1,any=1/,cpu/event=0xe,umask=0x1/'
                                  \___ Cannot find PMU `cpu'. Missing kernel support?
Run 'perf list' for a list of valid events

 Usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events
```

I'm calling toplev as follows:

```bash
toplev.py --force-cpu skx -I 500 --no-group -A --frequency -v -l 1 --quiet --csv , --output "$outdir/ft.perf.csv" --summary "$outdir/fasttree.sh" "$1"
```

It sounds like this is a ``perf`` issue (compatibility with GCP?) rather than a ``pmu-tools`` issue, so if that's the case, I'll investigate elsewhere :-)

**Comment by andikleen** [comment]
On Fri, May 08, 2020 at 09:11:54AM -0700, Niema Moshiri wrote:
>     That's another preproduction CPU, right?
> 
> Not too sure; this is a Google Cloud Platform VM. Sorry for my inexperience :-)
> I'm collaborating with some hardware people, and they asked me for some
> profiling info about my runs

Ah I think that's actually production. I'll add support.
 
> 
>     You can use --force-cpu skx
> 
> I tried that, and now I get the following error:
> 
> Cannot open /root/.cache/pmu-events/GenuineIntel-6-55-uncore.json
> Cannot open /root/.cache/pmu-events/GenuineIntel-6-55-uncore.json
> event syntax error: '..ref-cycles,cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0x9c,umask=0x1/,cpu/event=0xc2,umask=0x2/,cpu/event=0xd,umask=0x1,any=1/,cpu/event=0xe,umask=0x1/'
>                                   \___ Cannot find PMU `cpu'. Missing kernel support?


This means the VM didn't export Perfmon to the guest. You would need
to contact Google to change the settings of the VMs. toplev requires
an exposed PMU.

Probably toplev could give a better error message for such a case.


-Andi

**Comment by michaelrun** [comment]
I also met similiar issue on AliCloud VM in China:
```event syntax error: '{cpu/event=0xa4,umask=0x1/,cpu/event=0xad,umask=0x10/..'
                     \___ Cannot find PMU `cpu'. Missing kernel support?
Run 'perf list' for a list of valid events

 Usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events
cpu: Nothing measured for  0 1 10 11 12 13 14 15 2 3 4 5 6 7 8 9
No node crossed threshold
```
