### ISSUE TITLE
  return res[index][cpuoff] IndexError: tuple index out of range

### ISSUE THREAD

**Issue by inevity** [andikleen/pmu-tools#19]
ubuntu
cpu: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
kernel :Linux ubuntu 3.16.0-31-generic

root@ubuntu:~/pmu-tools# toplev.py -l2 -p 2004
Running in HyperThreading mode. Will measure complete system.
Using level 2.
perf stat -x, -e '{cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0xe,umask=0x1/,cpu/event=0x9c,umask=0x1/,cpu/event=0xd,umask=0x3,cmask=1,any=1/,cpu/event=0xc2,umask=0x2/},{cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0xa3,umask=0x6,cmask=6/,cycles,cpu/event=0xa2,umask=0x8/,cpu/event=0x9c,umask=0x1,cmask=4/},{cpu/event=0x3c,umask=0x0,any=1/,instructions,cpu/event=0x9c,umask=0x1/,cycles,cpu/event=0x9c,umask=0x1,cmask=4/},{cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0xe,umask=0x1/,cpu/event=0x79,umask=0x30/,cpu/event=0xc2,umask=0x2/},{cpu/event=0xc5,umask=0x0/,cpu/event=0xc3,umask=0x1,edge=1,cmask=1/},{cpu/event=0xb1,umask=0x1,cmask=2/,cycles,cpu/event=0xa3,umask=0x4,cmask=4/,cpu/event=0xb1,umask=0x1,cmask=1/,cpu/event=0xb1,umask=0x1,cmask=3/},{cpu/event=0xa3,umask=0x6,cmask=6/,cpu/event=0xa2,umask=0x8/,cpu/event=0x5e,umask=0x1/,instructions}' -A -a -p 2004
7                            ---->print index     in code./pmu-tools/toplev.py 915 line
(11946234493.0,) ----->print res[index] 
0                          ---->print cpuoff 
then repeat
6
(3199005707.0,)
0

7
(11946234493.0,)
1

Traceback (most recent call last):
  File "/root/pmu-tools/toplev.py", line 1377, in <module>
    ret = execute(runner, out, rest)
  File "/root/pmu-tools/toplev.py", line 728, in execute
    print_keys(runner, res, rev, out, interval, env)
  File "/root/pmu-tools/toplev.py", line 682, in print_keys
    runner.print_res(r, rev[cpus[0]], out, interval, core_fmt(core), env, Runner.SMT_yes, stat)
  File "/root/pmu-tools/toplev.py", line 1161, in print_res
    obj.compute(lambda e, level:
  File "/root/pmu-tools/ivb_server_ratios.py", line 637, in compute
    self.val = (STALLS_MEM_ANY(EV, 2) + EV("RESOURCE_STALLS.SB", 2)) / CLKS(EV, 2 )
  File "/root/pmu-tools/ivb_server_ratios.py", line 71, in STALLS_MEM_ANY
    return EV(lambda EV , level : min(EV("CPU_CLK_UNHALTED.THREAD", level) , EV("CYCLE_ACTIVITY.STALLS_LDM_PENDING", level)) , level )
  File "/root/pmu-tools/toplev.py", line 1162, in <lambda>
    lookup_res(res, rev, e, obj, env, level, stat.referenced))
  File "/root/pmu-tools/toplev.py", line 902, in lookup_res
    for off in range(cpu.threads)])
  File "/root/pmu-tools/ivb_server_ratios.py", line 71, in <lambda>
    return EV(lambda EV , level : min(EV("CPU_CLK_UNHALTED.THREAD", level) , EV("CYCLE_ACTIVITY.STALLS_LDM_PENDING", level)) , level )
  File "/root/pmu-tools/toplev.py", line 901, in <lambda>
    lookup_res(res, rev, ev, obj, env, level, referenced, off), level)
  File "/root/pmu-tools/toplev.py", line 919, in lookup_res
    return res[index][cpuoff]
IndexError: tuple index out of range

we think the cpuoff =1 out of rang because of that the res[index] only have one member.

How can we fix the bug?

Thanks

**Comment by andikleen** [comment]
Did you press Ctrl-C? It currently doesn't deal well with partial input data.
Also -p doesn't work with SMT mode, need to forbid that. It always needs global measurements with SMT.

SMT mode measures globally anyways, so you can use sleep XXX while running the workload.

**Comment by inevity** [comment]
Yes,i use Ctrl-C.
Ok,i will try using sleep.
