### ISSUE TITLE
perf topdown l1 Breakdown Results Sum Up to Higher than 100%, also different result from toplev

### ISSUE THREAD

**Issue by takhandipu** [andikleen/pmu-tools#203]
Hello,

I was running a java workload using following command,

`perf stat --topdown -x, -C 0 taskset -c 0  java -jar ~/tools/java/benchmarks/renaissance-gpl-0.10.0.jar naive-bayes`, the corresponding breakdown is,

```
core,cpus,retiring,bad speculation,frontend bound,backend bound
S0-C0,1,151.0,3.9,26.0,,
```

If we sum the breakdown for each category, it is around 180.9 which higher than 100%. What could be reason for this?

Moreover, this result is completely different from results obtained using toplev wrapper using command `toplev.py -l1 --core C0 taskset -c 0 -- java -jar ~/tools/java/benchmarks/renaissance-gpl-0.10.0.jar naive-bayes`,

```
S1-C0    BE             Backend_Bound:   % Slots         59.45 <==
	This category represents fraction of slots where no uops are
	being delivered due to a lack of required resources for
	accepting new uops in the Backend...
```
No other categories are not even mentioned may be toplev filters them out as they are below 10% threshold. Also, note that Backend_bound was not even mentioned on the `perf stat --topdown` command results. What am I doing wrong here? If not, How to interpret this result?

My perf version is, 4.15.18
My hardware is, Intel(R) Xeon(R) Gold 6230 CPU (Cascade Lake)
My java workload's single-core (`taskset -c 0`) execution time is,

```
real	2m12.255s
user	2m1.230s
sys	0m10.622s
```

Thank you in advance for your help.

Tanvir.

**Comment by andikleen** [comment]
You cannot use -C 0 with --topdown on a SMT system. It needs to measure the whole core for SMT. -C 0 would be only one thread. Icelake will fix that.

Without -C0 it should match toplev output

**Comment by takhandipu** [comment]
Great! It works. Thanks for pointing out the mistake and the results now make sense as well. The command, `perf stat --topdown -x, -C 0,40 taskset -c 0,40 java -jar ~/tools/java/renaissance-gpl-0.10.0.jar naive-bayes -r 1` shows the breakdown as,

```
core,cpus,retiring,bad speculation,frontend bound,backend bound,
S0-C0,2,51.6,4.4,22.3,21.7,
```

While the command, `toplev.py -l1 --core S0-C0 -x, -v taskset -c 0,40 java -jar ~/tools/java/renaissance-gpl-0.10.0.jar naive-bayes -r 1` shows the breakdown as,
```
S0-C0,Frontend_Bound,18.61,% Slots below,This category represents fraction of slots where the processor's Frontend undersupplies its Backend...,frontend_retired.latency_ge_8:pp,0.00,100.0,
S0-C0,Bad_Speculation,4.70,% Slots below,This category represents fraction of slots wasted due to incorrect speculations...,,0.00,100.0,
S0-C0,Backend_Bound,23.96,% Slots,This category represents fraction of slots where no uops are being delivered due to a lack of required resources for accepting new uops in the Backend...,,0.00,100.0,<==
S0-C0,Retiring,52.72,% Slots below,This category represents fraction of slots utilized by useful work i...,,0.00,100.0,
S0-C0-T0,MUX,100.00,%,PerfMon Event Multiplexing accuracy indicator,,0.00,100.0,
S0-C0-T1,MUX,100.00,%,,,0.00,100.0,
```
Which are fairly similar. Thank you once again.
Tanvir.
