### ISSUE TITLE
Unknown CPU or CPU event map not found on cascadelake cpu

### ISSUE THREAD

**Issue by jaredzhu** [andikleen/pmu-tools#209]
Because of the network problem, I download the https://download.01.org/perfmon/mapfile.csv and https://download.01.org/perfmon/readme.txt to /root/.cache/pmu-events. And del the download code from the python script. While I execute the ./toplev.py, I get the error message:

**Unknown CPU or CPU event map not found.**

My server is cascadelake：

processor       : 79
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
stepping        : 7
microcode       : 0x5000024
cpu MHz         : 1199.546
cache size      : 28160 KB
physical id     : 1
siblings        : 40
core id         : 28
cpu cores       : 20

**Comment by andikleen** [comment]
You would need to download the json files too.

If you can't download on the target system run event_download -a on some other system and copy the complete pmu-events directory over
