### ISSUE TITLE
Support per core / per thread / per socket output for a single run

### ISSUE THREAD

**Issue by andikleen** [andikleen/pmu-tools#213]
Allow multiple --per-* flags.

Support an option to output to different files with -o by adding postfixes

**Comment by andikleen** [comment]
Implemented

**Comment by senior7515** [comment]
a link to the commit would be helpful to see how to use

**Comment by andikleen** [comment]
Just specify multiple per-* flags together

https://github.com/andikleen/pmu-tools/commit/6f7f3d3124412da5fa9175e2ceef989611c520bf
