### ISSUE TITLE
Data collection about HyperThread/SMT

### ISSUE THREAD

**Issue by SimonDyl** [andikleen/pmu-tools#22]
1. "-p/--pid mode not compatible with SMT. Use sleep in global mode." why? It's affected by perf? 
    I had gotten  a answer from Intel vtune engineer, SMT can compatible with -p.

2. when computing Core actual clocks, and smt_enabled is true, however, the value nearly equal between "CPU_CLK_UNHALTED.THREAD:amt1" and ""CPU_CLK_UNHALTED.THREAD". Is it normal phenomenon?

# Core actual clocks
def CORE_CLKS(EV, level):
    return (EV("CPU_CLK_UNHALTED.THREAD:amt1", level) / 2) if smt_enabled else CLKS(EV, level)

Thank you! :)

**Comment by andikleen** [comment]
On Fri, May 29, 2015 at 08:28:53PM -0700, SimonDyl wrote:
> 1. "-p/--pid mode not compatible with SMT. Use sleep in global mode." why? It's affected by perf? 
>     I had gotten  a answer from Intel vtune engineer, SMT can compatible with -p.

In SMT mode toplev needs to see both threads at the same time, and that is not guaranteed
with --pid.

> 
> 2. when computing Core actual clocks, and smt_enabled is true, however, the value nearly equal between "CPU_CLK_UNHALTED.THREAD:amt1" and ""CPU_CLK_UNHALTED.THREAD". Is it normal phenomenon?

Are both threads busy?

-- 
ak@linux.intel.com -- Speaking for myself only.
