### ISSUE TITLE
toplev: negative percentages reported for L2_Bound

### ISSUE THREAD

**Issue by fudyfan** [andikleen/pmu-tools#230]
@2016choang and I ran toplev on a few workloads and consistently found that negative percentages were being reported for `Backend_Bound.Memory_Bound.L2_Bound`. How can we fix this issue? 

For context, we ran toplev on a machine with the Haswell processor and Linux kernel version 5.0.13.

Thanks in advance for looking into this issue! If any additional context would be helpful, please let us know!

**Comment by andikleen** [comment]
That's a known problem on Haswell (HSM63 in the spec update) Should be fixed in Broadwell. No workaround, sorry. But I'll look at making toplev print a warning.
