### ISSUE TITLE
DRAM Bound MEM_Bandwidth Formula

### ISSUE THREAD

**Issue by samhsia** [andikleen/pmu-tools#265]
For TopDown, I'm wondering where the formula for MEM_Bandwidth comes from.

The metric itself is described in pmu-tools as "fraction of cycles where the core's performance was likely hurt due to approaching bandwidth limits of external memory (DRAM)" and implemented with "OFFCORE_REQUESTS_OUTSTANDING.ALL_DATA_RD:c4". 

From the original TopDown paper the MEM_Bandwidth bottleneck is described as "whenever the occupancy of requests exceeds ~70% of max number of requests the memory controller can serve simultaneously". I'm not sure how this event implements that.

Thank you so much!

**Comment by andikleen** [comment]
This is an occupancy event.  :c4 (called cmask in the documentation) 
means that there are 4 or more events per cycle. So it means it's the number of cycles are more than 4 entries in the queue.
If you divide total cycles by this you get a percentage of congestion.
This is a fairly standard way to determine queue congestion.

**Comment by samhsia** [comment]
I see - so basically we're saying that if there are more than 4 entries in this super queue in a given cycle, then we're marking that cycle for queue congestion (bandwidth bottleneck). Makes sense.

I guess what I'm curious about is how we arrived at using 4 entries as the threshold. Given that in the paper (and in Intel's optimization reference manual) they mention a "70% of max number of requests" number. Is there documentation on this size of the super queue?

Thanks!

**Comment by andikleen** [comment]
Not that I know of.
