### ISSUE TITLE
Provide option for leader sampling

### ISSUE THREAD

**Issue by sunkuranganath** [andikleen/pmu-tools#268]
Today jevents does not provide leader sampling option to pass set of events as a group and have one of the events chosen as a leader. While this is available in low level Perf API - the group leader could be sent across via file descriptor using perf_format_read, its not available today as a feature in jevents. Request to provide option to choose a leader event when a group of events are being passed.

**Comment by andikleen** [comment]
I just wanted to verify you still need this. This is only useful if you actually sample, not just count. For counting no leader is needed and the existing group mechanism in libjevents should work.

**Comment by sunkuranganath** [comment]
Not needed anymore. will close this.
