### ISSUE TITLE
Enhanced logging & reporting

### ISSUE THREAD

**Issue by sunkuranganath** [andikleen/pmu-tools#269]
This is to request generic set of improvements to logging & reporting to help improve understanding of accuracy of events provided
Requests:
- To indicate in the logs when time based multiplexing happens for a group of events provided
- To provide a log message indicating the leader event from a group of events when multiplexing happens
- To provide list of events that were actually sampled and the list of events that were multiplexed. This could be provided as an "additional attribute" to already existing reporting structure. This in turn helps understand accuracy of events
- To provide 'PMU Name' on which the corresponding event was counted

**Comment by andikleen** [comment]
> To indicate in the logs when time based multiplexing happens for a group of events provided

This is not supported by perf, would need new kernel enhancements or parsing of the low level MSR tracing logs.

> To provide a log message indicating the leader event from a group of events when multiplexing happens

The leader is always the event that was specified in the perf_event_open call, so it should be already known.

>To provide list of events that were actually sampled and the list of events that were multiplexed. This could be provided as an >"additional attribute" to already existing reporting structure. This in turn helps understand accuracy of events

The multiplexing for each event is reported as the enabled/running data in the perf API. I think that's what you are asking for.

>To provide 'PMU Name' on which the corresponding event was counted

This has been implemented now with jevent_pmu_name()

**Comment by sunkuranganath** [comment]
Thanks for the response.
