### ISSUE TITLE
ucevent.py fails with the new perf stat csv output format

### ISSUE THREAD

**Issue by tootoonchian** [andikleen/pmu-tools#27]
The new perf stat csv output (https://lwn.net/Articles/653941/) breaks ucevent.py.

The assertion on line 601 of ucevent.py (`assert evp[0] == j`) fails because `measure()` includes the new stats printed after the event name as part of the event name: e.g., in a sample run `evp[0]` is `'uncore_imc_0/event=0x4,umask=0x3/,103357003,10.39'` rather than `'uncore_imc_0/event=0x4,umask=0x3/'`.

**Comment by andikleen** [comment]
Fixed
