### ISSUE TITLE
Detect platform generation & automatically download json event lists

### ISSUE THREAD

**Issue by sunkuranganath** [andikleen/pmu-tools#270]
Currently users of jevents as a library have to either download json event lists from 01.org manually or run event_download.py seperately.
Could the jevents library be modified to download the json event lists automatically based on detecting the platform generation? This would help deploy the library in cloud orchestrated environments and make it easy to use the library instead of performing additional steps to download the json event lists.

**Comment by andikleen** [comment]
The feedback I got from a lot of users was that they prefer to distribute the event lists on their own because the cloud nodes often don't have full internet access. But I can see there might be some who prefer it fully automatic.

I guess could add a function that does the download, but I would prefer not to have a dependency on a full http library.

Would a function that executes curl be acceptable?

**Comment by sunkuranganath** [comment]
Thanks @andikleen  for considering this.
You are right in production type environments. Especially for reference deployments or lab environments, its assumed to have internet access to download and setup the relevant files either via scripts or manually.

From that perspective, there could be a choice provided to either download the files automatically via curl or user could do it themselves.
So a function that executes curl should be good. Thanks for providing this.

**Comment by sunkuranganath** [comment]
One question along similar lines, updates to json event lists happen periodically and posted onto 01.org. Considering the fact that we always want to use latest json event lists, could jevents be the right place to have a periodic check of latest event lists?
If json event lists are downloaded at deploy time and they end up being updated on 01.org at run time, we would end up using old/incorrect event lists.

**Comment by sunkuranganath** [comment]
The implementation is considerably heavy and not currently being asked by customer.
Closing this.
