### ISSUE TITLE
toplev crashes

### ISSUE THREAD

**Issue by psteinb** [andikleen/pmu-tools#31]
saw this with a76c89a7ba2c0dd5fa9feec7616d3a926931cfb5
```
$ ~/software/pmu-tools/repo/toplev.py -l1 sleep 10
Using level 1.
perf stat -x, -e 'task-clock,{cpu/event=0xc2,umask=0x2/,cpu/event=0xe,umask=0x1/,cpu/event=0xd,umask=0x3,cmask=1/,cpu/event=0x9c,umask=0x1/,cycles}' sleep 10
Traceback (most recent call last):
  File "/home/steinbac/software/pmu-tools/repo/toplev.py", line 1748, in <module>
    ret = execute(runner, out, rest)
  File "/home/steinbac/software/pmu-tools/repo/toplev.py", line 960, in execute
    print_keys(runner, res, rev, valstats, out, interval, env)
  File "/home/steinbac/software/pmu-tools/repo/toplev.py", line 885, in print_keys
    cores = [key_to_coreid(x) for x in res.keys() if int(x) in runner.allowed_threads]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by psteinb** [comment]
it's really strange, I went as far as 1 month back (a62cabe050eda35c94d506e3d6511ba4ebd4765b) and the error prevails ... did the format of the ~/.cache files changes or something?? can anyone check, please? I checked all of the above on 2 haswell boxes (centos 7 and ubuntu 14.04).

**Comment by psteinb** [comment]
phew, it seems to work as root! before anyone asks, `kernel.perf_event_paranoid=-1` is already set. I'd be happy for a comment before this issue is closed.

**Comment by andikleen** [comment]
Can you show the raw perf output for both cases? Just run the perf stat ... command line toplev prints

**Comment by andikleen** [comment]
I assume this is fixed. Please reopen if the problem is still there.
