### ISSUE TITLE
toplev: incorrectly blames Retiring

### ISSUE THREAD

**Issue by aayasin** [andikleen/pmu-tools#342]
In the below reproducer, toplev points to Retiring as the bottleneck marking it with <== while it does not cross its threshold.
I've noticed it in few cases, but when -l1 is used the issue does not apply (2nd command). Might be related to multiplexing.

    $ toplev.py --no-desc -vl2 ./pmu-tools/workloads/BC1s
    Using level 2.
    # 4.11-full-perf on Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz [skl]
    FE             Frontend_Bound                      % Slots                    6.7 <
    BAD            Bad_Speculation                     % Slots                   36.7
    BE             Backend_Bound                       % Slots                    7.2 <
    RET            Retiring                            % Slots                   51.1   <==
    FE             Frontend_Bound.Fetch_Latency        % Slots                    3.1 <
    FE             Frontend_Bound.Fetch_Bandwidth      % Slots                    3.7 <
    BAD            Bad_Speculation.Branch_Mispredicts  % Slots                   35.3
    BAD            Bad_Speculation.Machine_Clears      % Slots                    0.0 <
    BE/Mem         Backend_Bound.Memory_Bound          % Slots                    2.1 <
    BE/Core        Backend_Bound.Core_Bound            % Slots                    5.1 <
    RET            Retiring.Light_Operations           % Slots                   50.2 <
    RET            Retiring.Heavy_Operations           % Slots                    0.9 <
    MUX                                                %                         11.9
    Add --nodes '!+Retiring*/2,+MUX' for breakdown on the bottleneck.
    
    $ toplev.py --no-desc -vl1 ./pmu-tools/workloads/BC1s
    Using level 1.
    # 4.11-full-perf on Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz [skl]
    FE             Frontend_Bound   % Slots                    6.8 <
    BAD            Bad_Speculation  % Slots                   35.5   <==
    BE             Backend_Bound    % Slots                    7.2 <
    RET            Retiring         % Slots                   50.5 <
    MUX                             %                        100.0
    Add --nodes '!+Bad_Speculation*/2,+MUX' for breakdown on the bottleneck.

**Comment by andikleen** [comment]
On Thu, Oct 15, 2020 at 03:59:09PM -0700, aayasin wrote:
> In the below reproducer, toplev points to Retiring as the bottleneck marking it
> with <== while it does not cross its threshold.
> I've noticed it in few cases, but when -l1 is used the issue does not apply
> (2nd command). Might be related to multiplexing.

It should be already fixed by 

256c1ca toplev: Only force thresh for not measured parents

The problem was the reference to Heavy_Operations, which was forced to
true because it was not enabled.

**Comment by aayasin** [comment]
I still see it with latest pmu-tools

**Comment by andikleen** [comment]
On Sat, Oct 17, 2020 at 10:26:21AM -0700, aayasin wrote:
> I still see it with latest pmu-tools

On what CPU?

Please double check you have

% git log --online toplev.py 
....
256c1ca toplev: Only force thresh for not measured parents


On Skylake I see

./toplev ./workloads/BC1s 
Using level 1.
# 4.11-full-perf on Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz [skl]
BAD            Bad_Speculation  % Slots                   34.9  <==
        This category represents fraction of slots wasted due to
        incorrect speculations...
Add --nodes '!+Bad_Speculation*/2,+MUX' for breakdown on the bottleneck.

**Comment by aayasin** [comment]
This is on SKL. Note you have to use -vl2 to reproduce it. 

It sounds I'm on latest bits:

    ... /perf-tools/pmu-tools$ git log toplev.py | grep -B4 parents
    commit 256c1ca733e2d2ffd032455d9106b759330a3acc
    Author: Andi Kleen <andi@firstfloor.org>
    Date:   Tue Oct 13 17:18:52 2020 -0700
    
        toplev: Only force thresh for not measured parents
    --

**Comment by andikleen** [comment]
On Mon, Oct 19, 2020 at 03:49:21PM -0700, aayasin wrote:
> This is on SKL. Note you have to use -vl2 to reproduce it.

Ah I see it now with -vl2. Will look into it.
