### ISSUE TITLE
mapfile.csv unavailable, pmu-tools can't be used by first time users.

### ISSUE THREAD

**Issue by bitcharmer** [andikleen/pmu-tools#350]
The hosting for event map files you guys use is hosed:

./event_download.py -a                                                                                                                                                        Sat 24 Oct 2020 20:40:51 BST
Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
retrying download
retrying download
Cannot access event server: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)>

If you need a proxy to access the internet please set it with:
	export https_proxy=http://proxyname...
If you are not connected to the internet please run this on a connected system:
	event_download.py '*'
and then copy ~/.cache/pmu-events to the system under test
To get events for all possible CPUs use:
	event_download.py -a
Traceback (most recent call last):
  File "./event_download.py", line 262, in <module>
    print("Nothing found", file=sys.stderr, onlyprint=args.print_)
TypeError: 'onlyprint' is an invalid keyword argument for this function

The site is just unavailable which renders pmu-tools useless for all first-time users.

**Comment by andikleen** [comment]
Seems to work for me. I guess it was a temporary glitch. Please retry.

**Comment by bitcharmer** [comment]
Thanks. I tried 3 different browsers and 2 different OSes to access https://download.01.org/perfmon/mapfile.csv.
No luck until I switched to VPN and used a German exit node (I live in the UK). Strange.
Appreciate the awesome work you do on linux kernel. Thank you.
