### ISSUE TITLE
toplev: misses output for power metrics

### ISSUE THREAD

**Issue by aayasin** [andikleen/pmu-tools#365]
reproducible on SKL and ICL:

    $ toplev.py --no-desc -l0 -v --power --perf -- ./pmu-tools/workloads/PYTHON1s
    Running with --power. Will measure complete system.
    Using level 0.Change level with -lX
    
    perf stat -x\; -e power/energy-cores/,power/energy-pkg/,power/energy-gpu/ -a ./pmu-tools/workloads/PYTHON1s
    # 4.11-full-perf on Genuine Intel(R) CPU 0000 @ 1.20GHz [icl/icelake]
    MUX                            %                        100.0

**Comment by andikleen** [comment]
Works for me now. Please reopen if there is still a problem
