### ISSUE TITLE
The results with --no-multiplex and without --no-multiplex are much different.

### ISSUE THREAD

**Issue by yanx21** [andikleen/pmu-tools#370]
Hi
    I used toplev to analyze my programs, and I found that the results with --no-multiplex and without --no-multiplex are much different.

Here are the result:

---
1st test group
`toplev -l1 -v --no-desc --global A.out`
```txt
# 4.1-full-perf on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz [skx]
FE             Frontend_Bound   % Slots                   32.9 <
BAD            Bad_Speculation  % Slots                    5.3 <
BE             Backend_Bound    % Slots                   53.8   <==
RET            Retiring         % Slots                    8.0
MUX                             %                         33.3
```
---
2nd test group
`toplev -l1 -v --no-desc --global --no-multiplex A.out`
```txt
# 4.1-full-perf on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz [skx]
FE             Frontend_Bound   % Slots                   61.7   <==
BAD            Bad_Speculation  % Slots                    7.8 <
BE             Backend_Bound    % Slots                   20.0
RET            Retiring         % Slots                   10.5
MUX                             %                        100.0
```
---
I ran the test several times and the results were pretty much the same.
What's more, I also tried with different level, and couldn't get the consistent results.

So I'm confused about the result, which test should I rely on? with --no-multiplex or without it?

Thanks.

**Comment by andikleen** [comment]
There could be multiple reasons:
- --no-multiplex assumes that the program repeatably deterministically runs in the same way, and also that there is no background load on the system. For example you can double check that multiple runs have the same number of instructions and the same IPC.
- When the program has a lot of phases that have different characteristics then multiplexing can cause large errors. It may help to run it longer or change the setup to reduce phases.
- A common problem is that the initialization phase is quite different. It may help to skip it with --delay
- You could experiment with the multiplexing frequency in /sys/devices/cpu/perf_event_mux_interval_ms
