### ISSUE TITLE
Running the pmu-tools within the  CoreOS of an OCP cluster    

### ISSUE THREAD

**Issue by MelGHub** [andikleen/pmu-tools#373]
Hello
Trying to capture the perf events within the cores using the default "perf" command, I see the following

# perf stat -e L1-dcache-loads,L1-dcache-load-misses,L1-dcache-stores ls
bin  boot  dev  etc  home  host  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
 Performance counter stats for ‘ls’:
 not supported      L1-dcache-loads
not supported      L1-dcache-load-misses
not supported      L1-dcache-stores
       0.001842826 seconds time elapsed
       0.000945000 seconds user
       0.000942000 seconds sys

Cloned the "pmu-tools" from this repo and was able to start the "ocperf" within the CoreOS ( running inside the toolbox container), where it can pull the initial code 

Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
Downloading https://download.01.org/perfmon/SKX/skylakex_core_v1.24.json to GenuineIntel-6-55-4-core.json
Downloading https://download.01.org/perfmon/readme.txt to readme.txt
Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
Downloading https://download.01.org/perfmon/SKX/skylakex_core_v1.24.json to GenuineIntel-6-55-4-core.json
Downloading https://download.01.org/perfmon/SKX/skylakex_matrix_v1.24.json to GenuineIntel-6-55-4-offcore.json
Downloading https://download.01.org/perfmon/SKX/skylakex_uncore_v1.24.json to GenuineIntel-6-55-4-uncore.json

however when trying to run the "./ocperf stat -e cycles,instructions,cache-references,cache-misses,bus-cycles ls"

still seeing the same issue

# ./ocperf stat -e cycles,instructions,cache-references,cache-misses,bus-cycles ls
perf stat -e cycles,instructions,cache-references,cache-misses,bus-cycles ls
CHANGES.md   bdw-cpuinfo           cputop.py           frequency.py          interval-normalize     knl_ratios.py     msr.py         parallel-tester     pmudef.pyc            slm_ratios.py         tl-xlsx.py    toplev.ico
COPYING      bdw_client_ratios.py  csv_formats.py      gen-dot.py            interval-normalize.py  latego.py         msr.pyc        parser              pmumon.py             snb_client_ratios.py  tl_cpu.py     toplev.man
Makefile     bdx_server_ratios.py  event-rmap.py       gen_level.py          interval-plot          latego.pyc        node.py        pci.py              power_metrics.py      test-uncore.json      tl_io.py      toplev.py
PYLINT       cleanlogs             event-translate.py  hsw_client_ratios.py  interval-plot.py       linux_metrics.py  objutils.py    pci.pyc             requirements.txt      tester                tl_output.py  topology
README.md    clx_server_ratios.py  event_download      hsx_server_ratios.py  ivb_client_ratios.py   list-events.py    oc-all-events  pebs-grabber        simple-pebs           tl-barplot.py         tl_stat.py    tsx_metrics.py
TOOLS.md     counterdiff.py        event_download.py   icl_client_ratios.py  ivb_server_ratios.py   listutils.py      ocperf         perf_metrics.py     simple_ratios.py      tl-serve              tl_uval.py    ucevent
__pycache__  cpumap.sh             event_download.pyc  interval-merge        jevents                metrics.py        ocperf.py      plot-normalized.py  skl_client_ratios.py  tl-serve.py           tldata.py     utilized.py
all-tester   cputop                fake-perf.py        interval-merge.py     jkt_server_ratios.py   msr               other-tester   pmudef.py           skx_server_ratios.py  tl-tester             toplev        workloads

 Performance counter stats for 'ls':

   not supported      cycles                                                      
   not supported      instructions                                                
   not supported      cache-references                                            
   not supported      cache-misses                                                
   not supported      bus-cycles                                                  

       0.001696681 seconds time elapsed

       0.000000000 seconds user
       0.001707000 seconds sys

running the "toplev" shows the following message

# ./toplev.py -l2 ls
Will measure complete system.
Using level 2.
event syntax error: '{cpu/event=0x9c,umask=0x1/,cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0xc2,umask=0x2/,cpu/event=0xe,umask=0x1/,cpu/event=0xd,umask=0x1,any=1/},{cpu/event=0x9c,umask=0x1,cmask=4/,cpu/event=0x3c,umask=0x0,..'
                     \___ Cannot find PMU `cpu'. Missing kernel support?
Run 'perf list' for a list of valid events

 Usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events
No node crossed threshold

the CoreOS is at 

sudo rpm-ostree status
State: idle
Deployments:
● pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ed113a254eac95322283e85e411276ab948c7061c763737aed84d7f3e3929fc7
              CustomOrigin: Managed by machine-config-operator
                   Version: 47.83.202103140039-0 (2021-03-14T00:42:30Z)
             LocalPackages: kernel-headers-4.18.0-240.el8.x86_64 kernel-devel-4.18.0-240.el8.x86_64

  pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ed113a254eac95322283e85e411276ab948c7061c763737aed84d7f3e3929fc7
              CustomOrigin: Managed by machine-config-operator
                   Version: 47.83.202103140039-0 (2021-03-14T00:42:30Z)

**Comment by andikleen** [comment]
On Wed, Apr 14, 2021 at 09:33:04AM -0700, MelGHub wrote:
> Hello
> Trying to capture the perf events within the cores using the default "perf"
> command, I see the following
> 
> perf stat -e L1-dcache-loads,L1-dcache-load-misses,L1-dcache-stores ls
> 
> bin boot dev etc home host lib lib64 lost+found media mnt opt proc root run
> sbin srv sys tmp usr var
> Performance counter stats for ‘ls’:
> L1-dcache-loads
> L1-dcache-load-misses
> L1-dcache-stores
> 0.001842826 seconds time elapsed
> 0.000945000 seconds user
> 0.000942000 seconds sys

There are no event counts in the output?

> 
> Cloned the "pmu-tools" from this repo and was able to start the "ocperf" within
> the CoreOS ( running inside the toolbox container), where it can pull the
> initial code
> 
> Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
> Downloading https://download.01.org/perfmon/SKX/skylakex_core_v1.24.json to
> GenuineIntel-6-55-4-core.json
> Downloading https://download.01.org/perfmon/readme.txt to readme.txt
> Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
> Downloading https://download.01.org/perfmon/SKX/skylakex_core_v1.24.json to
> GenuineIntel-6-55-4-core.json
> Downloading https://download.01.org/perfmon/SKX/skylakex_matrix_v1.24.json to
> GenuineIntel-6-55-4-offcore.json
> Downloading https://download.01.org/perfmon/SKX/skylakex_uncore_v1.24.json to
> GenuineIntel-6-55-4-uncore.json
> 
> however when trying to run the "./ocperf stat -e
> cycles,instructions,cache-references,cache-misses,bus-cycles ls"
> 
> still seeing the same issue
> 
> ./ocperf stat -e cycles,instructions,cache-references,cache-misses,bus-cycles


ocperf won't make any difference for these perf events. It's only a
frontend to enable the intel style events (like instructions.retired
etc.)

> all-tester cputop fake-perf.py interval-merge.py jkt_server_ratios.py msr
> other-tester pmudef.py skx_server_ratios.py tl-tester toplev workloads
> 
> Performance counter stats for 'ls':
> 
> cycles
> instructions
> cache-references
> cache-misses
> bus-cycles
> 
>    0.001696681 seconds time elapsed
> 
>    0.000000000 seconds user
>    0.001707000 seconds sys
> 
> running the "toplev" shows the following message
> 
> ./toplev.py -l2 ls
> 
> Will measure complete system.
> Using level 2.
> event syntax error: '{cpu/event=0x9c,umask=0x1/,cpu/event=0x3c,umask=0x0,any=1
> /,cpu/event=0xc2,umask=0x2/,cpu/event=0xe,umask=0x1/,cpu/event=0xd,umask=
> 0x1,any=1/},{cpu/event=0x9c,umask=0x1,cmask=4/,cpu/event=0x3c,umask=0x0,..'
> ___ Cannot find PMU `cpu'. Missing kernel support?


Ok your container doesn't have /sys mounted or maybe perf disabled
(likely the later if you don't even see event counts)

To make any measurements you would need to fix that.
