### ISSUE TITLE
[Question] -p/--pid not compatible with SMT, is it specific to toplev or also not compatible in perf?

### ISSUE THREAD

**Issue by deciding** [andikleen/pmu-tools#385]
Hi,

I saw in a previous issue that, this option not compatible since, we cannot guarantee both the threads will be monitored simultaneously. For this restriction, I am wondering

1. is --pid also not a good choice in perf tool?
2. why this is not good only in the --pid mode?
3. is there any other workaround other than global mode sleep?

Thanks in advance!

**Comment by andikleen** [comment]
On Sun, Jul 25, 2021 at 01:56:48AM -0700, deciding wrote:
> Hi,
> 
> I saw in a previous issue that, this option not compatible since, we cannot
> guarantee both the threads will be monitored simultaneously. For this
> restriction, I am wondering
> 
>  1. is --pid also not a good choice in perf tool?

It depends on what you measure requires accounting for the full core or
not. There are a lot of metrics that work per thread, but full TMA
before Icelake requires full core.

>  2. why this is not good only in the --pid mode?
>  3. is there any other workaround other than global mode sleep?

One of:

- Use Icelake or newer which doesn't have this restriction for most
  nodes (except for a few nodes marked Core*)
- Disable SMT (cputop 'thread == 1' offline | sh as root)
- Make sure the siblings are idle (--singlethread on idle system)

**Comment by deciding** [comment]
@andikleen it's truly helpful. thx bro 👍
