### ISSUE TITLE
jevents and event_download.py not looking in same directory for JSON files

### ISSUE THREAD

**Issue by matthew-olson-intel** [andikleen/pmu-tools#393]
I've noticed that if I run a program using the `jevents` library with `sudo`, it won't find the JSON files that I downloaded with `event_download.py`. Even if I execute `event_download.py` as `sudo`, it'll place the JSON files in my normal user's directory (by checking the `SUDO_USER` environment variable).  I'll fix this by making `jevents` look at the `SUDO_USER` environment variable, exactly as `event_download.py` does.

I plan to write a PR to fix this as I find time.

**Comment by andikleen** [comment]
makes sense.

**Comment by matthew-olson-intel** [comment]
Created PR #394
