### ISSUE TITLE
How does pmu-tools handdle with events which only works on specific PMUs using Linux perf?

### ISSUE THREAD

**Issue by xiexiguo** [andikleen/pmu-tools#407]
Some events only work on specific PMU, such as "CYCLE_ACTIVITY.CYCLES_L1D_PENDING" only works on PMU2 on HaswellX platform.
```
  {
    "EventCode": "0xA3",
    "UMask": "0x08",
    "EventName": "CYCLE_ACTIVITY.CYCLES_L1D_PENDING",
    "BriefDescription": "Cycles with pending L1 cache miss loads.",
    "PublicDescription": "Cycles with pending L1 data cache miss loads. Set Cmask=8 to count cycle.",
    "Counter": "2",
    "CounterHTOff": "2",
    "SampleAfterValue": "2000003",
    "MSRIndex": "0",
    "MSRValue": "0",
    "TakenAlone": "0",
    "CounterMask": "8",
    "Invert": "0",
    "AnyThread": "0",
    "EdgeDetect": "0",
    "PEBS": "0",
    "Data_LA": "0",
    "L1_Hit_Indication": "0",
    "Errata": "0",
    "ELLC": "0",
    "Offcore": "0",
    "EVENT_STATUS": "0"
  },
```
As I known, I can not select which PMU to used which using linux perf. So, how does pmu-tools handdle with these events?
Using direct MSR programming?

**Comment by aayasin** [comment]
pmu-tools uses the perf tool to collect events. In doing so, it passes the event name and/or it’s programming details. The perf tool relies on the perf_events, which is part of the Linux kernel to schedule events on proper counters (while possibly accounting for other counter requests of the system). There is the part where the system maps the event to the proper counter. 
By default, counter multiplexing is employed by perf_events in case of contention.
