### ISSUE TITLE
Event download fails due to wrong tuple unpacking.

### ISSUE THREAD

**Issue by dhschall** [andikleen/pmu-tools#408]
When starting `toplev` the first time and the event lists are downloaded the parsing fails in line  [146](https://github.com/andikleen/pmu-tools/blob/93a31782131f907067339c883477075cfedb5451/event_download.py#L146) due to wrong tuple unwrapping

```
Traceback (most recent call last):
  File "/usr/local/pmu-tools/toplev", line 3781, in <module>
    version = runner_emaps()
  File "/usr/local/pmu-tools/toplev", line 3771, in runner_emaps
    runner.ectx.emap = ocperf.find_emap(pmu=runner.pmu if runner.pmu else "cpu")
  File "/usr/local/pmu-tools/ocperf.py", line 979, in find_emap
    return json_with_extra(el, eventmap_is_file, pmu)
  File "/usr/local/pmu-tools/ocperf.py", line 877, in json_with_extra
    name = event_download.eventlist_name(el, pmu_to_type[pmu])
  File "/usr/local/pmu-tools/event_download.py", line 232, in eventlist_name
    files = parse_map_file(name, key, acceptfile=True)
  File "/usr/local/pmu-tools/event_download.py", line 146, in parse_map_file
    cpu, version, name, typ = n
ValueError: too many values to unpack
```

**Comment by leonardvaney** [comment]
This fix still produces an error:
```
Traceback (most recent call last):
  File "/usr/local/pmu-tools/toplev", line 57, in <module>
    import ocperf
  File "/usr/local/pmu-tools/ocperf.py", line 70, in <module>
    import event_download
  File "/usr/local/pmu-tools/event_download.py", line 146
    cpu, version, name, typ, *_ = n
                             ^
SyntaxError: invalid syntax
```
However, if I also change the first line of the file pmu-tools/toplev with "python3" instead of "python" it does fix the problem.

**Comment by ustiugov** [comment]
@leonardvaney which python version do you use? @dhschall and you?

**Comment by dhschall** [comment]
I use python3 (3.8)

**Comment by dhschall** [comment]
> This fix still produces an error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/pmu-tools/toplev", line 57, in <module>
>     import ocperf
>   File "/usr/local/pmu-tools/ocperf.py", line 70, in <module>
>     import event_download
>   File "/usr/local/pmu-tools/event_download.py", line 146
>     cpu, version, name, typ, *_ = n
>                              ^
> SyntaxError: invalid syntax
> ```
> 
> However, if I also change the first line of the file pmu-tools/toplev with "python3" instead of "python" it does fix the problem.

**Comment by leonardvaney** [comment]
I used the the vhive-ubuntu20 profile with cloudlab nodes. This afternoon I tried to launch a new experiment to check the python version of the nodes but the command "python" is no longer recognized. I guess between now and yesterday someone modified the cloudlab profile?

**Comment by ustiugov** [comment]
@leonardvaney very unlikely

**Comment by andikleen** [comment]
Thanks for the fix. I fixed it differently because *_ is not compatible with python 2
