### ISSUE TITLE
incorrect event-counter scheduling on Icelake

### ISSUE THREAD

**Issue by aayasin** [andikleen/pmu-tools#414]
The events CYCLE_ACTIVITY.STALLS_L* are restricted to counters 0-3 starting Icelake PMU.
Latest toplev with TMA 4.3 support scheduled these two events twice in two groups:

- CYCLE_ACTIVITY.STALLS_L1D_MISS
- CYCLE_ACTIVITY.STALLS_L2_MISS
- CYCLE_ACTIVITY.STALLS_L3_MISS

One group schedules them on incorrect counters as highlighted in figure! [toplev-sched-icl](https://user-images.githubusercontent.com/16062350/149837489-822d2910-3f7b-4ea9-a886-854b217abc7f.JPG)

**Comment by andikleen** [comment]
Do you mean because they're in the end of the group? perf doesn't require the input to be the same order as what is put into the final counters, the kernel fixes it up. So I think that's ok.
