### ISSUE TITLE
toplev: should treat Core_Execution nodes too as Core-scoped

### ISSUE THREAD

**Issue by aayasin** [andikleen/pmu-tools#417]
The core_domain include teh 3 Core_Execution CountDomain nodes in TMA 4.3:

    $ grep domain pmu-tools/adl_glc_ratios.py | sort | uniq -c | sort -n | grep -i core
    3     domain = "Core_Execution"
    5     domain = "Core_Clocks"
    9     domain = "Core_Metric"

Which are currently excluded:
https://github.com/andikleen/pmu-tools/blob/30fd1e1a688f8d3b62fbc7762b44fdf3d380c6ae/toplev.py#L180

To avoid this re-happening again in future, I would probably remove that set and change predicate at:
https://github.com/andikleen/pmu-tools/blob/30fd1e1a688f8d3b62fbc7762b44fdf3d380c6ae/toplev.py#L2538

to something like: 

    def core_node(obj):
       dom = safe_ref(obj, 'domain')
       return dom.startswith("slots") or dom.startswith("core")

**Comment by andikleen** [comment]
Cannot just hard code it, that would break pre ICL which also needs
Slots. I committed a fix now thanks.
