### ISSUE TITLE
I cant get pebs-grabber to install

### ISSUE THREAD

**Issue by michaeldupton** [andikleen/pmu-tools#42]
I was able to build and install simple-pebs without issue.

This is on kernel 4.2.0-19

when I try pebs-grabber, I get an error.

dmegs says:
pebs_grabber: PEBS version 2
pebs_grabber: Cannot register kprobe: -2

**Comment by andikleen** [comment]
I pushed a fix. However pebs-grabber is really obsolete in newer kernels because perf can retrieve all information in the PEBS record natively. So you don't really need it anymore.
