### ISSUE TITLE
toplev: counter scheduling on ICL+ does not handle nmi watchdog fully

### ISSUE THREAD

**Issue by ak-intel** [andikleen/pmu-tools#430]
The scheduling assumes that the PMU has all 4 lower counters available for events that need to be scheduled on counter 0-3.

But the NMI watchdog could allocate one of those and then the groups wouldn't randomly fail.

toplev knows about the nmi watchdog today, but only reduces the total number of counters. 

Handling might need retry handling or probing the PMU with nmi watchdog on?

**Comment by aayasin** [comment]
Andi, it is better to move NMI watchdog to an upper counter on all products

**Comment by ak-intel** [comment]
Well I hope the moving to HPET series eventually goes in. Ricardo just posted a new version.
