### ISSUE TITLE
toplev failing to parse CPUs from sysfs

### ISSUE THREAD

**Issue by samkhn** [andikleen/pmu-tools#461]
toplev, regardless of parameters passed (including no parameters), throws an error with the following stack trace:
```bash
Traceback (most recent call last):
  File "toplev.py", line 3722, in <module>
    runner_list = init_runner_list()
                  ^^^^^^^^^^^^^^^^^^
  File "toplev.py", line 3699, in init_runner_list
    cpu_list = get_cpu_list(j)
               ^^^^^^^^^^^^^^^
  File "toplev.py", line 3671, in get_cpu_list
    return [k for k in read_cpus(fn) if use_cpu(k)]
                       ^^^^^^^^^^^^^
  File "toplev.py", line 3660, in read_cpus
    return parse_cpu_list(cpus.readline())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "toplev.py", line 3651, in parse_cpu_list
    if m.group(2):
       ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

```

Some notes:
- my cpus file is located at `/sys/devices/cpu_core/cpus`. The toplev script can't seem to find this.
- I am invoking via absolute path
- perf has permissions to read appropriate system events (safer alternative to paranoid), nmi_watchdog set to 0

Commit d0cbe52 added this section.

Related bug: https://github.com/andikleen/pmu-tools/issues/451

**Comment by andikleen** [comment]
So what does 

grep . /sys/devices/cpu*/cpus

output?

**Comment by andikleen** [comment]
I pushed ab497ac5d43f256bd67f21bcde5f2901226cac64 to avoid the error, but does toplev actually work after that?

**Comment by samkhn** [comment]
> So what does
> 
> grep . /sys/devices/cpu*/cpus
> 
> output?

Outputs:
```text
/sys/devices/cpu_core/cpus:0-11
```

**Comment by andikleen** [comment]
Thanks and does it work with latest master?

**Comment by andikleen** [comment]
Should be fixed. Please re-open if it does not work.
