### ISSUE TITLE
two events monitoring in simple-pebs.c

### ISSUE THREAD

**Issue by doru50** [andikleen/pmu-tools#462]
I use Intel cascade processor.
Is there any way to change code to monitor two events simultaneously?

I tried adding below definitions and some codes to use these, but I don't think it is the correct way to monitor two events. 
```
#define MSR_IA32_PERFCTR1           0x000000c2
#define MSR_IA32_EVNTSEL1           0x00000187
```

Could you give me some advise how to edit the code in simple-pebs.c to monitor two events?

**Comment by andikleen** [comment]
Every time simple-pebs programs or reads one counter program two. It is always the next MSR number. 
Or use a more capable PEBS driver like perf
