### ISSUE TITLE
percentages going over 100?

### ISSUE THREAD

**Issue by orm011** [andikleen/pmu-tools#47]
Hi there. First of all, thank you for the tools. I've learned a lot about how to use perf just by looking at how the pmu-tools do it.

I'm seeing this strange output in  commit d70840ba8d5017b, using  command line options ../pmu-tools/toplev.py --verbose --no-multiplex -l3 --single-thread -- ./myprogram

I consistently get this this printed output whose % is > 100 on a particular test program I am running.

BE      Backend_Bound:                                                        82.25 %           [100.00%]
BE/Mem  Backend_Bound.Memory_Bound:                                           57.41 %           [100.00%]
BE/Mem  Backend_Bound.Memory_Bound.L1_Bound:                                   5.58 %           [100.00%]
        This metric estimates how often the CPU was stalled without
        loads missing the L1 data cache...
        Sampling events:  mem_load_retired.l1_hit:pp mem_load_retired.fb_hit:pp
BE/Mem  Backend_Bound.Memory_Bound.L1_Bound.DTLB_Load:                  **_     196.05 %below  _**    [100.00%]
        This metric represents cycles fraction where the TLB was
        missed by load instructions...
        Sampling events:  mem_inst_retired.stlb_miss_loads:p

**Comment by orm011** [comment]
When not run with the --verbose flag, I see the following warning: 
"warning: Mismeasured: DTLB_Load". So maybe this is not an issue with pmu-tools but with the underlying counters?
Any guidance as to why this sort of thing would happen?

**Comment by andikleen** [comment]
A lot of the formulas only give meaningful results when their parent nodes crossed the threshold. You disabled that with -v. For more details on that see the Top Down paper (Yasin "A Top-Down method for ...")

**Comment by orm011** [comment]
I see. Thanks, I will look more closely into that.
