### ISSUE TITLE
Trunk version of toplev regressed in generation of valid groups

### ISSUE THREAD

**Issue by aayasin** [andikleen/pmu-tools#504]
Can be reproduced with PYTHON1s test:

Previous good toplev version (called old in below grep output) is [b85ebff](https://github.com/andikleen/pmu-tools/tree/b85ebffd2ef72e8e3a94ea9c76f55fdadf9a80d8)

    $ grep num run-tl-*stat
    run-tl-new.ICX.stat:num-zero-stats 12
    run-tl-new.ICX.stat:num-not_counted-stats 85
    run-tl-old.ICX.stat:num-zero-stats 97
    run-tl-old.ICX.stat:num-not_counted-stats 0

reproducer on ICX:
    $ /home/admin1/ayasin/perf-tools/pmu-tools/toplev.py --no-desc -vl6 --nodes '+IPC,+Instructions,+UopPI,+Time,+SLOTS,+CLKS,+Mispredictions,+Big_Code,+Instruction_Fetch_BW,+Branching_Overhead,+DSB_Misses,+Cache_Memory_Bandwidth,+Cache_Memory_Latency,+Memory_Data_TLBs,+Memory_Synchronization,+Compute_Bound_Est,+Irregular_Overhead,+Other_Bottlenecks,+Base_Non_Br' -V tl47-grouping-regress.toplev-vl6-perf.csv --frequency --metric-group +Summary --single-thread --tune 'DEDUP_NODE = "MEM_Parallel_Reads,Lock_Latency,Slots_Utilization,Power,L2_Bound,Big_Code,DSB_Misses,IC_Misses,Contested_Accesses,Data_Sharing,PMM_Bound,Memory_Operations,DRAM_Bound,Other_Light_Ops,Mispredictions,Cache_Memory_Bandwidth,Cache_Memory_Latency,Memory_Data_TLBs,Memory_Synchronization,Base_Non_Br,Instruction_Fetch_BW,Irregular_Overhead,Core_Bound_Likely,Branch_Misprediction_Cost,Other_Bottlenecks"' --perf-output tl47-grouping-regress.toplev-vl6-perf-output.csv -- ./pmu-tools/workloads/PYTHON1s tl47-grouping-regress
    
    $ grep -c 'not counted' tl47-grouping-regress.toplev-vl6-perf*
    tl47-grouping-regress.toplev-vl6-perf.csv:115
    tl47-grouping-regress.toplev-vl6-perf-output.csv:115

**Comment by andikleen** [comment]
Seems to be a problem with the test system
