### ISSUE TITLE
How to measure only the second part (a region) of a program?

### ISSUE THREAD

**Issue by FabianSchuetze** [andikleen/pmu-tools#509]
Thanks for this wonderful repo - it's a pleasure to work with it. 

I have a simple program that consists of two functions:

```c++
int main() {
    std::vector<float> data = preparation();
    Result res = calculation(data);
}
```
I am only interested in metrics related to the `calculation` function.  Can I use `toplev.py` in such cases? If so, how? 

I know roughly how long it takes to reach the `calculation` function. The [wiki](https://github.com/andikleen/pmu-tools/wiki/toplev-manual) mentions that command line argument `-D` and says: 

> We run this with level toplev, skipping the initialization phase (about 80 ms). This is a useful technique with short programs to get better measurements (I measured the initialization phase before by just printing the time at the top of the program)

However, I do not see the option `D` listed in the available command line arguments for [toplev.py](https://github.com/andikleen/pmu-tools/blob/master/toplev.py).

**Comment by andikleen** [comment]
The toplev help only lists the toplev arguments, but it supports any perf arguments too. -D is a perf argument.
