### ISSUE TITLE
rdpmc_read() in libjevents returns values > 2^48

### ISSUE THREAD

**Issue by nkurz** [andikleen/pmu-tools#51]
I've been trying to do something similar to the interrupts.c code, but was having trouble with rdpmc_read() giving seemingly nonsense results.  I've narrowed it down to the buf->offset field sometimes having a high bit set (1L << 48).  PERF_EVENT_IOC_RESET will both the counter and the offset to 0, but at some point buf->offset will jump back.    Masking off the high bits (or just ignoring offset) solves the problem but I can't find any reason it should be necessary. 

I don't know if this is a bug in rdpmc_read(), a bug in the kernel, or something I'm doing wrong.  I'm using a slightly older kernel (4.2.0) on Skylake, so it's also possible this is something that has already been fixed.    Test code against current pmu-tools master is here: https://github.com/nkurz/pmu-tools/tree/test-offset.   Help or suggestions of a better venue would be appreciated.  I can upgrade to the current kernel and retest if necessary.  Thanks!

**Comment by andikleen** [comment]
I think this one has been fixed recently with 30d4df60a6d4

Please reopen if it still happens.
