### ISSUE TITLE
ocperf: different values of cpu_clk_unhalted.thread_any within the same core

### ISSUE THREAD

**Issue by stefanodoni** [andikleen/pmu-tools#52]
Hi Andi,

I'm trying to measure the unhalted cycles on a core basis. I therefore used ocperf and selected the above mentioned event.

However, what I'm getting from ocperf is sort of weird. I was expecting to get the same values for the two threads that share the same core, however this not seem to be true.

$ sudo ./ocperf.py stat -e cpu_clk_unhalted.thread_any -a -A sleep 5
perf stat -e cpu/event=0x3c,umask=0x0,any=1,name=cpu_clk_unhalted_thread_any/ -a -A sleep 5

 Performance counter stats for 'system wide':

CPU0           627.912.025 cpu_clk_unhalted_thread_any                                   
CPU1           627.248.055 cpu_clk_unhalted_thread_any                                   
CPU2           529.161.153 cpu_clk_unhalted_thread_any                                   
CPU3           812.752.677 cpu_clk_unhalted_thread_any                                   

       5,001079353 seconds time elapsed

Any hint at what might be the culprit here?

Some info on my system:

OS: Ubuntu 14.04
CPU	: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz

Thank you!

**Comment by andikleen** [comment]
The cycles will be different if one thread goes idle.

**Comment by stefanodoni** [comment]
Ok,

I thought the any worked differently.

So to get the amount of unhalted cycles of the core, shall I use the max of
the two threads?

Thanks

**Comment by andikleen** [comment]
not an pmu-tools issue
