### ISSUE TITLE
Issue with '-v' flag

### ISSUE THREAD

**Issue by kusumakarb** [andikleen/pmu-tools#53]
I'm trying to run toplev.py with a docker container as a workload, I use the following command:

`python toplev.py  --core C0 -l1 -I 1000 -x, -o ../benchmarks/mediaStreamingLevel1I1000msC0.csv taskset -c 0 docker run -t --name=streaming_client -v /path/to/output:/output --volumes-from streaming_dataset --net streaming_network cloudsuite/media-streaming:client 172.18.0.2
`
When I run this the toplev is removing the '-v' flag present in the docker command which is causing errors. The output is:

`Will measure complete system`
`Using level 1.`
`perf stat -x\; -e`
`'{cpu/event=0x3c,umask=0x0,any=1/,cpu/event=0xe,umask=0x1/,cpu/event=0x9c,umask=0x1/,cpu/event=0xd,umask=0x3,any=1,cmask=1/,cpu/event=0xc2,umask=0x2/}' -I 1000 -C 0,18,36,54 -A -a taskset -c 0 docker run -t --name=streaming_client /path/to/output:/output --volumes-from streaming_dataset --net streaming_network cloudsuite/media-streaming:client 172.18.0.2`
`Unable to find image '/path/to/output:/output:latest' locally`

This might be happening as toplev also has the '-v ' flag (--verbose or -v). Without using toplev the docker container runs fine.

**Comment by andikleen** [comment]
Add -- after the toplev arguments to separate them
