### ISSUE TITLE
Problem with performance counters for Xeon D-1540

### ISSUE THREAD

**Issue by mentalm6t** [andikleen/pmu-tools#54]
The Xeon D-1540 appears to have a problem where only 4 of the 8 perf counters per core actually count, whereas the other 4 remain zero (with hyperthreading disabled). I experienced this issue and then saw that other people have had the same issue: https://software.intel.com/en-us/forums/software-tuning-performance-optimization-platform-monitoring/topic/560536

I don't know if this affects other processor in that family, but it obviously ends up giving bogus pmu-tools results for this family of processors when hyperthreading is disabled. Might want to check for that particular processor and then limit the number of counters per perf set to only 4.

Note that in addition to only 4 out of 8 counters available, the LLC counter values also have their own set of problems as described at that page (also confirmed with my CPU). There's actually a lot of counter-related problems with this processor...
http://www.intel.com/content/www/us/en/processors/xeon/xeon-d-1500-specification-update.html

**Comment by andikleen** [comment]
I don't think Xeon-D has such an issue. What you're likely seeing are side effects of the BDE70 erratum.
Future versions of toplev will flag nodes affected by such errata.
