### ISSUE TITLE
HSM31 on Xeon  v3 valid?

### ISSUE THREAD

**Issue by knweiss** [andikleen/pmu-tools#57]
I'm currently testing toplev.py on a Xeon v3 (Haswell) and see this output in level 2 system-wide test:

```
# ./toplev.py -l2 sleep 5
Will measure complete system.
Using level 2.
warning: removing Memory_Bound Core_Bound due to unsupported events in kernel:
CYCLE_ACTIVITY.CYCLES_NO_EXECUTE CYCLE_ACTIVITY.STALLS_LDM_PENDING
Use --force-events to override (may result in wrong measurements)
Nodes Memory_Bound Core_Bound have errata HSM31 and were disabled.
Override with --ignore-errata
```

Using the `--force-events` and `--ignore-errata` options works as a workaround. However, I'm wondering if the error is valid in the first place?

I see **HSM31** in the `~/.cache/pmu-events/GenuineIntel-6-3C-core.json`
file and find it in the [Intel 4th-gen-core mobile specification update](http://www.intel.ie/content/dam/www/public/us/en/documents/specification-updates/4th-gen-core-family-mobile-specification-update.pdf)
as **HSM31: Performance Monitor UOPS_EXECUTED Event May Undercount**.

However, I don't see HSM31 or anything UOPS_EXECUTED-related mentioned in the [Intel Xeon E5 v3 specification update](http://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/xeon-e5-v3-spec-update.pdf) for my processor at all.
So is this warning valid?

The CPU of my Haswell test system:
```
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
Stepping:              2
CPU MHz:               2888.281
BogoMIPS:              5010.61
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47
```
Running the latest CentOS 7.2 kernel:
```
# uname -a
Linux haswell1 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by andikleen** [comment]
I was a bit too aggressive on the errata filtering. This particular one is fairly harmless. I believe it exists on your CPU, but we can still use the event. I white listed relevant issues now.
