### ISSUE TITLE
Fix in ocperf

### ISSUE THREAD

**Issue by ohm314** [andikleen/pmu-tools#59]
Hallo,

I have a little fix to propose for the process_args function in ocperf.py:

```patch
From 21b152a29f59da03769d4db33df720123218de80 Mon Sep 17 00:00:00 2001
From: Omar Awile <omar.awile@cern.ch>
Date: Mon, 12 Sep 2016 10:17:11 +0200
Subject: [PATCH] Pass along optional argv parameter for this case too

---
 ocperf.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ocperf.py b/ocperf.py
index f9bc904..7b1c068 100755
--- a/ocperf.py
+++ b/ocperf.py
@@ -790,7 +790,7 @@ def process_args(emap, argv=sys.argv):
                                              True if record == yes else False, emap)
             cmd.append(prefix + event)
         elif argv[i][0:2] == '-c':
-            oarg, i, prefix = getarg(i, cmd)
+            oarg, i, prefix = getarg(i, cmd, argv=argv)
             if oarg == "default":
                 if overflow is None:
                     print >>sys.stderr,"""
```

cheers!

**Comment by andikleen** [comment]
What does this fix?

**Comment by ohm314** [comment]
This fixes the case when ocperf is used programmatically and the value for -c is given as the next item in the list rather than in the same string as -c

**Comment by andikleen** [comment]
Hmm, but getarg neither has a argv argument, nor does it reference argv (without sys). Are you sure there are no other changes in your tree?

https://github.com/andikleen/pmu-tools/blob/master/ocperf.py#L748

In fact it surprises me that the interpreter doesn't complain for passing this undeclared argument.
Also if it was changed the other callers probably would need to be changed too

**Comment by ohm314** [comment]
Yes, you are right of course. I see now that my branch is quite a bit ahead of your master. Let me bundle up the changes into one nice pull request and explain properly and then we can discuss.

Sorry, I was a bit too quick this morning...
