### ISSUE TITLE
CPU_STARTING and CPU_DYING no longer used in Linux 4.9

### ISSUE THREAD

**Issue by soramichi** [andikleen/pmu-tools#66]
Hi, thanks for the great tool!

`simple-pebs/simple-pebs.c` uses CPU_STARTING and CPU_DYING to allow CPUs to be hot-plugged,  but these macros are no longer used in Linux 4.9.
http://lxr.free-electrons.com/ident?v=4.9;i=CPU_STARTING

As this commit (https://git.kernel.org/cgit/linux/kernel/git/tip/tip.git/commit/?id=ee1e714b94521b0bb27b04dfd1728ec51b19d4f0) suggests, we should move to the new state machine mechanism to support hot-plugging for kernel 4.9 or later versions.

For most of the cases where CPU hot-plugging never happens, just delete the notifier call-backs like https://github.com/soramichi/pmu-tools/commit/d175a0b57d4f727e0b8d605a7c250561c5cc3ec2 should work.

**Comment by andikleen** [comment]
Should be fixed
