### ISSUE TITLE
Fails to compile in CentOS 6.5

### ISSUE THREAD

**Issue by benbenolson** [andikleen/pmu-tools#70]
`addr.c` uses the macro `PERF_ATTR_SIZE_VER1`, which isn't available in CentOS's version of `/usr/include/linux/perf_events.h`. However, it does have `PERF_ATTR_SIZE_VER0`, and compiles correctly when that is changed.  Not sure if that will cause issues with usage, however.

Also, `addr.c` doesn't compile with `gcc 4.4.7`, and I'm reasonably certain that it's because that file uses an anonymous union in a struct, which that version of GCC doesn't support (not even with `-std=c11`, which isn't a supported option in this version).  Upgrading my GCC to one that was compiled in this decade fixes the issue, without any source code modification other than the replaced macro above.

**Comment by andikleen** [comment]
addr.c already uses VER0. resolve.c uses VER1 for the config2 field. Did you mean that file?
Unfortunately the VER1 is needed for some configurations, but I can add a define.

**Comment by andikleen** [comment]
Also addr.c has no unions, so I'm not sure where the anonymous union should be?

**Comment by benbenolson** [comment]
Yeah, sorry, I meant `resolve.c`. You're right.

`addr.c` uses `struct perf_event_attr`, which has anonymous unions in it. When I compile it with GCC 4.4.7, it fails because it can't find the fields in the struct that are in one of those unions. However, as I said, a newer version of GCC fixes this.

I'm now happily using the program, it works perfectly after changing that one line in `resolve.c` and compiling with a new version of GCC. Thanks!

**Comment by andikleen** [comment]
The shipped compiler should be able to handle everything in /usr/include/linux because that was needed to build the kernel.

Perhaps you used some options that disabled gnu extensions?

**Comment by andikleen** [comment]
no feedback. assuming  this is fixed.
