### ISSUE TITLE
tabs and spaces inconsistent

### ISSUE THREAD

**Issue by mbrucher** [andikleen/pmu-tools#71]
Hi,
From a fresh checkout from master:
  File "pmu-tools/toplev.py", line 147
    e = e[:e.find(":")]
                      ^
TabError: inconsistent use of tabs and spaces in indentation

And indeed, sometimes there are tabs, and sometimes spaces, and Python 3 doesn't like it.

**Comment by andikleen** [comment]
I removed all the tabs.

In general python 3 compatibility is not a goal of pmu-tools however.

**Comment by mbrucher** [comment]
Thanks. It's not just about Python3 compatibility. It's also about good practices (see PEP8).
Still, as Python 2 is phased out, it's a bad idea not to support Python 3.
