### ISSUE TITLE
GenuineIntel-6-4F-core.json not found

### ISSUE THREAD

**Issue by VinInn** [andikleen/pmu-tools#72]
on a Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
Downloading https://download.01.org/perfmon/BDX/BroadwellX_core_V10.json to GenuineIntel-6-4F-core.json
Cannot access event server: HTTP Error 404: Not Found

still
ocperf.py list does produce a reasonable list of events supported on Broadwell
and 
ocperf.py stat works with my "standard" list of Broadwell events...

**Comment by andikleen** [comment]
I fixed it, will be a day or so until it is updated.
