### ISSUE TITLE
perfpd doesn't seem to handle MMAP2

### ISSUE THREAD

**Issue by jrmuizel** [andikleen/pmu-tools#73]
Running perfpd doesn't seem to properly symbolize perf.data files that contain MMAP2

**Comment by andikleen** [comment]
mmap2 is implemented.

There are some issues with multiple events however. Perhaps you ran into that.

**Comment by jrmuizel** [comment]
https://github.com/andikleen/pmu-tools/blob/master/parser/mmap.py seems to check specifically for 'MMAP' and these tests will fail for 'MMAP2'

**Comment by andikleen** [comment]
Yes that is true. Does it work when you just check for MMAP2? The contents should be the same.

FWIW parser and the data model have all kind of rough edges and wasn't quite finished. That's why it is undocumented. Perhaps it is still useful however

**Comment by andikleen** [comment]
Should be all fixed now
