### ISSUE TITLE
Measure individual Metrics

### ISSUE THREAD

**Issue by hlitz** [andikleen/pmu-tools#74]
How can I measure single (or multiple) toplev metrics, e.g. Frontend_Latency ? This avoids counter multiplexing and makes the results better readable.

**Comment by andikleen** [comment]
You can only filter the output, but not which nodes are measured.  That would be dangerous because the bottleneck could be somewhere else. You can however use --no-multiplex if the workload is repeatable

  --nodes NODES         Include or exclude nodes (with + to add, ^ to remove,
                        comma separated list, wildcards allowed)
