### ISSUE TITLE
Can not run PMU-TOOLS on Linux kernel 3.11.0

### ISSUE THREAD

**Issue by Gumi-presentation-by-Dzh** [andikleen/pmu-tools#77]
I get two different kernel version, one is 3.11.0 and the other is 3.10.0-123.el7.x86_64.

But there is no PMU file in /sys/devices/ so the PMU TOOL dosen't work well.

But when I choose the kernel version in 3.10.0-514.10.2.el7.x86_64, the pmu file in clearly in my /sys/devices, and the PMU-TOOL is also work well.

So , is there some wrony in My kernel configuration?

**Comment by Gumi-presentation-by-Dzh** [comment]
My /sys/devices/ directory doesn't contain any uncore_* files. 

how can i install/add these files? Is there away to run PMU-TOOL without these devices?

**Comment by Gumi-presentation-by-Dzh** [comment]
When I use lspci | grep Performance

7f:08.2 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 QPI Link 0 (rev 04)
7f:09.2 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 QPI Link 1 (rev 04)
7f:0b.1 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 R3 QPI Link 0 & 1 Monitoring (rev 04)
7f:0b.5 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 R3 QPI Link 2 Monitoring (rev 04)
7f:0b.6 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 R3 QPI Link 2 Monitoring (rev 04)
7f:10.1 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCIe Ring Interface (rev 04)
7f:12.1 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 Home Agent 0 (rev 04)
7f:12.5 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 Home Agent 1 (rev 04)
ff:08.2 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 QPI Link 0 (rev 04)
ff:09.2 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 QPI Link 1 (rev 04)
ff:0b.1 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 R3 QPI Link 0 & 1 Monitoring (rev 04)
ff:0b.5 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 R3 QPI Link 2 Monitoring (rev 04)
ff:0b.6 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 R3 QPI Link 2 Monitoring (rev 04)
ff:10.1 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCIe Ring Interface (rev 04)
ff:12.1 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 Home Agent 0 (rev 04)
ff:12.5 Performance counters: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 Home Agent 1 (rev 04)

The Performance counters are available but there are nothing in my /sys/devices

[liao@node1-centos7 devices]$ ls -d /sys/devices/uncore_*
ls: cannot access /sys/devices/uncore_*: No such file or directory

**Comment by Gumi-presentation-by-Dzh** [comment]
We also have a disscution in Intel Development zone https://software.intel.com/node/738156

**Comment by andikleen** [comment]
The 3.10 kernel is a redhat kernel which has a lot of features backported.
3.11 and 3.16 are ancient kernels at this point which don't support new hardware.
Try 4.12
