### ISSUE TITLE
Better metric explanations for novices - give examples

### ISSUE THREAD

**Issue by milianw** [andikleen/pmu-tools#79]
Hello Andi,

would it be possible to add more in-depth explanations to the various metrics, such that novices like me can grasp the output of toplev better? Some examples:

```
BE/Core        Backend_Bound.Core_Bound.Ports_Utilization:         40.25 % Clocks [  6.25%]
        This metric estimates cycles fraction the CPU performance
        was potentially limited due to Core computation issues (non
        divider-related)...
```

What is a "Core computation issue"?

```
BE/Core        Backend_Bound.Core_Bound:           21.88 % Slots [ 16.51%]
        This metric represents slots fraction where Core non-memory
        issues were of a bottleneck...
```

Again, can you give examples for such issues?

Grepping the code, I see that for some metrics, you have added examples which is extremely useful. But some seem to be missing a more in-depth data.

Also, shouldn't these texts (and the others) say "fraction of cycles/slots" instead of "cycles/slots fraction"?

**Comment by milianw** [comment]
I just found `--long-desc`, which solves the first part of this issue I think. The grammatical error should still be fixed, I guess.

**Comment by aayasin** [comment]
Hello Milian,
Thanks for the report. We will address the grammatical error in next revision (TMA 3.4). 

Ahmad Yasin

**Comment by andikleen** [comment]
Fixed
