### ISSUE TITLE
Any plans to cut an official release branch?

### ISSUE THREAD

**Issue by maryamtahhan** [andikleen/pmu-tools#82]
Hi @andikleen 

are there any plans to cut an official release branch for pmu-tools?

thanks in advance
Maryam

**Comment by andikleen** [comment]
On Thu, Oct 12, 2017 at 09:02:10AM +0000, Maryam Tahhan wrote:
> Hi @andikleen
> 
> are there any plans to cut an official release branch for pmu-tools?

pmu-tools is on a rolling release, so you can always use the git tree.

I occasionally do tags, but only to get zip files for git challenged
users. They don't really mean anything.

-Andi
