### ISSUE TITLE
Race condition in resolve_event()

### ISSUE THREAD

**Issue by hannesweisbach** [andikleen/pmu-tools#88]
Initialisation of the `eventlist` hash table is racy in resolve_event(). If multiple threads call `resolve_event()` concurrently, a thread might set `eventlist_init` to true, before loading the JSON file. Immediately after that a thread might check `eventlist_init` and proceed to use `eventlist`, when it is in fact not properly initialised yet.
I assumed multithreaded access would be ok, from the documentation of rdpmc_open: "Must be called for each thread using the counter."

I'd be willing to supply a patch. How do you want to fix this issue? Have an explicit `jevents_init()` function or block until the initialisation is done?

**Comment by andikleen** [comment]
We already have read_events(NULL) exported, which would be jevents_init.
Also would be fine to add a jevents_init that does that.

I would prefer to not make jevents dependent on a locking library at this point.

Should document this in the documentation though. Could you send a patch for that?

**Comment by hannesweisbach** [comment]
Good to know ;)
I've added a section to thread README.md; see PR #89.

**Comment by andikleen** [comment]
Fixed
