### ISSUE TITLE
API about TSX

### ISSUE THREAD

**Issue by TheSilentDawn** [andikleen/pmu-tools#90]
I saw pmu-tools support TSX. I want to know if pmu-tools support get TSX abort message and virtual address of instruction that trigger tsx abort as perf? And can this be done in real time when target program running?

**Comment by andikleen** [comment]
There's no special API for it in pmu-tools, but yes it could be done through jevents.

You set up a self monitoring perf event with jevents for tx-abort and precise level 2 with a mmap buffer. On a abort there will be a perf record in the mmap buffer containing the abort IP.
